export default function robots() {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: [
        '/admin',
        '/settings',
        '/settings/',
        '/dashboard',
        '/wallet',
        '/checkout',
        '/library',
        '/history',
        '/watch-again',
        '/hearts',
        '/liked',
        '/watch-later',
        '/stats',
        '/notifications',
        '/messages',
        '/subscriptions',
        '/analytics',
        '/channel',
        '/vods',
        '/studio-tools',
        '/stream-settings',
        '/verify',
        '/advertiser-portal',
        '/playlist/',
      ],
    },
    sitemap: 'https://calabi.us/sitemap.xml',
    host: 'https://calabi.us',
  }
}
