/**
 * Smoke checks for follow-up audit items — no Vite imports needed.
 */
import assert from 'node:assert/strict'
import { readFileSync, existsSync } from 'node:fs'

const adEngine = readFileSync('src/lib/adEngine.js', 'utf8')
const vastAds = readFileSync('src/lib/vastAds.js', 'utf8')
const watchPage = readFileSync('src/components/WatchPage.jsx', 'utf8')
const liveIngest = readFileSync('src/lib/liveIngest.js', 'utf8')
const org = readFileSync('src/lib/orgConfig.js', 'utf8')
const liveAds = readFileSync('src/lib/liveAds.js', 'utf8')

assert.match(org, /productName: 'calabi'/)
const authBrand = readFileSync(new URL('../src/lib/authBrand.js', import.meta.url), 'utf8')
assert.match(authBrand, /calabi/)
assert.doesNotMatch(authBrand, /from Clips/)
const dashShell = readFileSync(new URL('../src/components/dash/DashboardShell.jsx', import.meta.url), 'utf8')
assert.doesNotMatch(dashShell, /<<<<<<< HEAD/)
const appSrc = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
assert.doesNotMatch(appSrc, /<<<<<<< HEAD/)

assert.match(adEngine, /ADSENSE_KEEP_STREAM_PIP|getAdSenseClientId/)
assert.match(vastAds, /VAST ads removed/)
assert.doesNotMatch(watchPage, /useVideoVastAds/)
assert.doesNotMatch(watchPage, /VideoInStreamAd/)
assert.match(liveIngest, /LIVE_INGEST_CONNECTED/)
assert.match(liveIngest, /URLs alone must never invent/)
assert.match(liveIngest, /Share a window or camera/)
const shortsStage = readFileSync('src/components/ShortsStage.jsx', 'utf8')
assert.match(shortsStage, /calc\(\(100dvh-3\.5rem\)\*9\/16\)/)
assert.doesNotMatch(shortsStage, /absolute right-4 top-1\/2/)
const shortsFeed = readFileSync('src/components/ShortsFeed.jsx', 'utf8')
assert.match(shortsFeed, /objectFit: 'cover'/)
const mediaUpload = readFileSync('src/lib/mediaUpload.js', 'utf8')
assert.match(mediaUpload, /ALLOWED_VIDEO_TYPES/)
assert.match(mediaUpload, /isAllowedUploadFile/)
assert.match(mediaUpload, /deleteHostedMedia/)
const contentService = readFileSync('src/lib/contentService.js', 'utf8')
assert.match(contentService, /Sign in to import/)
const importModal = readFileSync('src/components/ImportShortModal.jsx', 'utf8')
assert.match(importModal, /not the video file/)
const scriptsCat = readFileSync('src/data/supabaseScripts.js', 'utf8')
assert.match(scriptsCat, /0027_videos_visibility_rls_storage/)
assert.match(scriptsCat, /0028_clips_bucket_limits/)
assert.equal(existsSync('supabase/migrations/0028_clips_bucket_limits.sql'), true)
assert.equal(existsSync('docs/STORAGE.md'), true)
const adminPortal = readFileSync('src/components/AdminPortal.jsx', 'utf8')
assert.match(adminPortal, /isPlatformOwner\(user\) \|\| isAdminSession\(user\)/)
assert.doesNotMatch(adminPortal, /clips_admin_ui_unlocked/)
assert.doesNotMatch(watchPage, /dangerouslySetInnerHTML/)
assert.equal(liveAds.includes('LIVE_VIEWER_AD_DELAY_SEC = 0'), true)
assert.equal(existsSync('src/components/AdUnits.jsx'), false)
assert.equal(existsSync('src/hooks/useVideoVastAds.js'), false)

console.log('followup-smoke: ok')
