/** Live-project smoke checks — no mock catalog, no invented checkout grant. */
import { readFileSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { extractHashtags, mergeTags, parseClock, parseCaptionCues, isReleased, filterExploreItems, formatPostedAt, olderIso, postedAtOf } from '../src/lib/mediaMeta.js'
import { parseRoute, buildHash } from '../src/lib/routes.js'
import { makePublicId, isShortPublicId, looksLikeContentId, allocatePublicId } from '../src/lib/publicId.js'
import { sanitizeAuthError, normalizePhone } from '../src/lib/authBrand.js'
import { findOwnerLogin, isLocalOwnerLogin, isOwnerAccount, OWNER_LOGIN, ownerCloudEmails } from '../src/data/ownerLogin.js'
import { parseVastXml, parseVastClock, videoInStreamBreaks, EXOCLICK_VAST_URL, videoVastAdsEnabled } from '../src/lib/vastAds.js'
import { mixFeedAds, mixClipFeedRows, mixPicFeedRows, getActiveAdForVideo, adsAreRunning } from '../src/lib/adEngine.js'
import { featuredWindowStart, nextFeaturedRefreshAt, lastHourRange, interleaveHourlyHits, HOURLY_PATTERN, HOURLY_VIDEO_COUNT, HOURLY_CLIP_COUNT, HOURLY_PIC_COUNT } from '../src/lib/hourWindow.js'

let failed = 0
function assert(cond, msg) {
  if (!cond) {
    failed += 1
    console.error('FAIL', msg)
  } else {
    console.log('ok', msg)
  }
}

assert(sanitizeAuthError('Invalid login credentials') === 'Wrong email or password.', 'branded login error')
assert(!/supabase/i.test(sanitizeAuthError('supabase provider is not enabled')), 'errors never say supabase')
assert(normalizePhone('5551234567') === '+15551234567', 'us phone to e164')

assert(extractHashtags('hello #Music and #gaming').join(',') === 'music,gaming', 'hashtags')
assert(mergeTags('music, extra', 'more #music #live').includes('live'), 'merge tags')
assert(parseClock('1:02') === 62, 'parse clock')
const now = Date.parse('2026-08-24T12:00:00.000Z')
assert(formatPostedAt(now, now) === 'just now', 'brand new post is just now')
assert(formatPostedAt(now - 3600_000, now) === '1 hour ago', 'same-day post keeps relative hours')
assert(formatPostedAt(now - 36 * 3600_000, now) === '1 day ago', 'yesterday keeps days')
assert(formatPostedAt('', now) === '', 'missing date is blank not just now')
assert(olderIso('1969-07-24T16:00:00.000Z', new Date(now).toISOString()) === '1969-07-24T16:00:00.000Z', 'cloud now does not erase real date')
assert(formatPostedAt(postedAtOf({ id: 'org-nasa-iss', origin: 'public-domain-org', createdAt: '1969-07-24T16:00:00.000Z' })) === '', 'library 1969 stamp is blank not fake today')
assert(formatPostedAt(postedAtOf({ id: 'user-1', createdAt: '1969-12-31T00:00:00.000Z' })) === '', 'epoch junk dates are blank not fake today')
assert(parseCaptionCues('00:00.000 --> 00:02.000\nHi').length === 1, 'vtt cues')
assert(isReleased({ status: 'draft' }) === false, 'draft hidden')
assert(isReleased({ status: 'published' }) === true, 'published visible')
assert(isReleased({ status: 'scheduled', scheduledFor: new Date(Date.now() + 864e5).toISOString() }) === false, 'future schedule hidden')

const { kind, id, params } = parseRoute('#/watch/abc?t=12')
assert(kind === 'watch' && id === 'abc' && params.t === '12', 'watch timestamp route')
assert(buildHash('watch', 'abc', { t: 12 }) === '/abc?t=12', 'watch share is bare /id with t')
assert(buildHash('watch', 'abc') === '/abc', 'video share is calabi.us/id style')
assert(buildHash('clips', 'xyzClip99aa') === '/xyzClip99aa', 'clip share is bare /id')
assert(buildHash('pic', 'photoIdHere1') === '/photoIdHere1', 'pic share is bare /id')
assert(buildHash('clips') === '/clips', 'clips feed path unchanged')
assert(!buildHash('watch', 'abc').includes('#'), 'share paths do not use hash')
const pathParsed = parseRoute('/watch/abc?t=12')
assert(pathParsed.kind === 'watch' && pathParsed.id === 'abc' && pathParsed.params.t === '12', 'pathname watch route')
const bare = parseRoute('/fnf48rth348')
assert(bare.kind === 'content' && bare.id === 'fnf48rth348', 'bare /id is a content share link')
assert(buildHash('home') === '/', 'home is slash')
{
  const pid = makePublicId(11)
  assert(pid.length === 11 && isShortPublicId(pid), 'public ids are 11 letter/number chars')
  assert(looksLikeContentId(pid), 'public ids look like content')
  assert(!looksLikeContentId('clips'), 'reserved paths are not content ids')
  assert(allocatePublicId(() => false).length >= 11, 'allocatePublicId returns an id')
}
const publishIdSrc = readFileSync(new URL('../src/lib/contentService.js', import.meta.url), 'utf8')
assert(publishIdSrc.includes('newContentId'), 'video publish uses opaque public ids')
assert(!publishIdSrc.includes('`up_${Date.now()'), 'video publish no longer uses up_ timestamp ids')
const picsIdSrc = readFileSync(new URL('../src/lib/picsService.js', import.meta.url), 'utf8')
assert(picsIdSrc.includes('newContentId'), 'photo publish uses opaque public ids')

// Ads removed — stubs must stay no-op (BUG-008 / cleanup)
assert(videoVastAdsEnabled() === false, 'VAST ads stay disabled')
assert(adsAreRunning() === false, 'ad engine reports ads are not running')
assert(getActiveAdForVideo('any') == null, 'no campaign ads for videos')
assert(videoInStreamBreaks(600).length === 0, 'in-stream break schedule is empty')
assert(parseVastClock('00:00:05.0') === 0, 'vast clock stub returns 0')
assert(parseVastXml('<VAST/>') == null, 'vast parser stub returns null')
assert(EXOCLICK_VAST_URL === '', 'exoClick vast URL stub is empty')
{
  const fake = Array.from({ length: 10 }, (_, i) => ({ id: `c${i}` }))
  const mixed = mixFeedAds(fake, 'clip-feed')
  assert(mixed.length === fake.length && mixed.every((r) => r.kind === 'item'), 'mixFeedAds passes clips through with no ad rows')
  assert(mixClipFeedRows(fake).length === fake.length, 'mixClipFeedRows stub keeps clip count')
  assert(mixPicFeedRows(fake).length === fake.length, 'mixPicFeedRows stub keeps pic count')
}
assert(!existsSync(new URL('../src/components/AdUnits.jsx', import.meta.url)), 'AdUnits component removed')
assert(!existsSync(new URL('../src/components/ExoClickDisplay.jsx', import.meta.url)), 'ExoClickDisplay removed')
assert(!existsSync(new URL('../src/components/AdminAds.jsx', import.meta.url)), 'AdminAds panel removed')
assert(!existsSync(new URL('../src/hooks/useVideoVastAds.js', import.meta.url)), 'useVideoVastAds hook removed')
assert(!existsSync(new URL('../src/lib/feedAdCadence.js', import.meta.url)), 'feedAdCadence removed')
assert(!readFileSync(new URL('../src/components/ShortsFeed.jsx', import.meta.url), 'utf8').includes('mixFeedAds'), 'clips player has no ad mixer')
assert(!readFileSync(new URL('../src/components/PicsPage.jsx', import.meta.url), 'utf8').includes('InFeedAd'), 'pics viewer has no in-feed ads')
assert(!readFileSync(new URL('../src/components/WatchPage.jsx', import.meta.url), 'utf8').includes('useVideoVastAds'), 'watch page has no VAST hook')
assert(!readFileSync(new URL('../src/components/LiveView.jsx', import.meta.url), 'utf8').includes('Snooze ads'), 'live host has no ad snooze controls')
assert(existsSync(new URL('../public/_redirects', import.meta.url)), 'static host rewrites unknown paths to the app')
assert(readFileSync(new URL('../public/_redirects', import.meta.url), 'utf8').includes('/index.html'), 'redirects file serves index.html')
{
  const yaml = readFileSync(new URL('../render.yaml', import.meta.url), 'utf8')
  assert(yaml.includes('runtime: node') || yaml.includes('next start'), 'render blueprint runs Next.js on Node for SEO')
  assert(yaml.includes('npm run build'), 'render blueprint builds the app')
}
assert(existsSync(new URL('../netlify.toml', import.meta.url)), 'netlify spa fallback is present')
assert(readFileSync(new URL('../vite.config.js', import.meta.url), 'utf8').includes('spa-index-fallback'), 'vite fallback kept for legacy builds')
assert(existsSync(new URL('../app/layout.jsx', import.meta.url)), 'Next.js App Router layout exists')
assert(existsSync(new URL('../app/content/[id]/page.jsx', import.meta.url)), 'content pages have SEO metadata route')
assert(existsSync(new URL('../app/SiteChrome.jsx', import.meta.url)), 'SEO marketing pages use SiteChrome')
assert(readFileSync(new URL('../app/about/page.jsx', import.meta.url), 'utf8').includes('AboutPage'), 'about route SSRs AboutPage')
assert(readFileSync(new URL('../app/content/[id]/page.jsx', import.meta.url), 'utf8').includes('<article'), 'content route includes SEO article HTML')
assert(readFileSync(new URL('../app/sitemap.js', import.meta.url), 'utf8').includes('fetchRecentContentIds'), 'sitemap includes recent content ids')
assert(!existsSync(new URL('../public/sitemap.xml', import.meta.url)), 'no static public/sitemap.xml overriding App Router sitemap')
assert(!existsSync(new URL('../public/robots.txt', import.meta.url)), 'no static public/robots.txt overriding App Router robots')
assert(existsSync(new URL('../middleware.js', import.meta.url)), 'middleware rewrites bare content ids for SEO')
assert(readFileSync(new URL('../package.json', import.meta.url), 'utf8').includes('"next"'), 'Next.js is a dependency')
assert(readFileSync(new URL('../package.json', import.meta.url), 'utf8').includes('"build": "next build"'), 'default build is Next.js')
assert(readFileSync(new URL('../src/components/AdminSetup.jsx', import.meta.url), 'utf8').includes('Render') && readFileSync(new URL('../src/components/AdminSetup.jsx', import.meta.url), 'utf8').includes('Node'), 'admin setup documents the Node Render host')
// Phase 3: section routes + Next router sync (BUG-005 / BUG-006)
for (const section of ['clips', 'pics', 'live', 'explore', 'creators', 'create', 'advertise', 'support']) {
  assert(existsSync(new URL(`../app/${section}/page.jsx`, import.meta.url)), `section route /${section} exists`)
  assert(
    readFileSync(new URL(`../app/${section}/page.jsx`, import.meta.url), 'utf8').includes('sectionMetadata'),
    `/${section} exports section SEO metadata`,
  )
}
assert(existsSync(new URL('../app/sectionMeta.js', import.meta.url)), 'shared sectionMeta helper exists')
assert(existsSync(new URL('../src/lib/NextNavContext.jsx', import.meta.url)), 'NextNavContext bridges App Router')
assert(readFileSync(new URL('../app/SpaShell.jsx', import.meta.url), 'utf8').includes('NextNavContext'), 'SpaShell provides NextNavContext')
assert(readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8').includes('useNextNav'), 'App consumes Next router')
assert(readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8').includes('nextNav.router.push'), 'App navigates via router.push')
// Phase 4: home SSR + profile SEO + noindex private shells
assert(readFileSync(new URL('../app/page.jsx', import.meta.url), 'utf8').includes('fetchRecentContent'), 'home SSRs recent content list')
assert(readFileSync(new URL('../app/page.jsx', import.meta.url), 'utf8').includes('<section'), 'home includes crawler section HTML')
assert(existsSync(new URL('../app/profile/[handle]/page.jsx', import.meta.url)), 'profile SEO route exists')
assert(readFileSync(new URL('../app/profile/[handle]/page.jsx', import.meta.url), 'utf8').includes('fetchProfileByHandle'), 'profile route loads creator metadata')
assert(readFileSync(new URL('../src/lib/contentServer.js', import.meta.url), 'utf8').includes('fetchRecentCreatorHandles'), 'contentServer can list creator handles')
assert(readFileSync(new URL('../app/sitemap.js', import.meta.url), 'utf8').includes('fetchRecentCreatorHandles'), 'sitemap includes creator profiles')
for (const privateRoute of ['dashboard', 'settings', 'library']) {
  assert(existsSync(new URL(`../app/${privateRoute}/page.jsx`, import.meta.url)), `/${privateRoute} App Router page exists`)
  assert(
    readFileSync(new URL(`../app/${privateRoute}/page.jsx`, import.meta.url), 'utf8').includes('sectionMetadata'),
    `/${privateRoute} uses sectionMetadata`,
  )
}
// Finish: remaining known shells + dynamic SEO routes
for (const route of [
  'watch', 'community', 'content-rules', 'creator-apply', 'playlists',
  'wallet', 'vods', 'analytics', 'channel', 'subscriptions', 'studio-tools',
  'stream-settings', 'history', 'watch-again', 'hearts', 'liked', 'watch-later',
  'stats', 'notifications', 'checkout', 'verify', 'advertiser-portal', 'admin',
]) {
  assert(existsSync(new URL(`../app/${route}/page.jsx`, import.meta.url)), `finish route /${route} exists`)
}
assert(existsSync(new URL('../app/sound/[id]/page.jsx', import.meta.url)), 'sound/[id] SEO route exists')
assert(existsSync(new URL('../app/tag/[id]/page.jsx', import.meta.url)), 'tag/[id] SEO route exists')
assert(existsSync(new URL('../app/playlist/[id]/page.jsx', import.meta.url)), 'playlist/[id] route exists')
assert(readFileSync(new URL('../app/shorts/page.jsx', import.meta.url), 'utf8').includes("redirect('/clips')"), 'shorts redirects to clips')
assert(readFileSync(new URL('../app/robots.js', import.meta.url), 'utf8').includes('/notifications'), 'robots disallows private surfaces')
assert(readFileSync(new URL('../app/sectionMeta.js', import.meta.url), 'utf8').includes('noindex'), 'sectionMeta supports noindex shells')
assert(readFileSync(new URL('../app/[[...slug]]/page.jsx', import.meta.url), 'utf8').includes('Last-resort'), 'catch-all is last-resort only')

function isPromoLive(promo, now = Date.now()) {
  if (!promo || promo.published !== true) return false
  if (promo.startsAt) {
    const t = new Date(promo.startsAt).getTime()
    if (t && t > now) return false
  }
  if (promo.endsAt) {
    const t = new Date(promo.endsAt).getTime()
    if (t && t < now) return false
  }
  return true
}
assert(isPromoLive({ published: false }) === false, 'unpublished promo hidden')
assert(isPromoLive({ published: true }) === true, 'published promo live')
assert(isPromoLive({ published: true, startsAt: new Date(Date.now() + 864e5).toISOString() }) === false, 'future promo hidden')

function startPremiumCheckout({ already = false, configured = false, link = '' } = {}) {
  if (already) return { granted: false, status: 'already' }
  if (link) return { granted: false, status: 'redirect', url: link }
  if (configured) return { granted: false, status: 'key_ready' }
  return { granted: false, status: 'no_key_in_build' }
}
assert(startPremiumCheckout({}).granted === false, 'checkout never grants without charge')
assert(startPremiumCheckout({ already: true }).status === 'already', 'already subscribed')
assert(startPremiumCheckout({ configured: true }).status === 'key_ready', 'key without payment link')
assert(startPremiumCheckout({ link: 'https://buy.stripe.com/x' }).status === 'redirect', 'payment link redirects')

const explore = filterExploreItems([
  { id: '1', createdAt: new Date().toISOString(), durationSec: 30, views: 2 },
  { id: '2', createdAt: new Date(Date.now() - 40 * 864e5).toISOString(), durationSec: 500, views: 9 },
], { date: 'week', duration: 'short' })
assert(explore.length === 1 && explore[0].id === '1', 'explore date+duration filter')

const checkoutSrc = readFileSync(new URL('../src/lib/checkout.js', import.meta.url), 'utf8')
const pageSrc = readFileSync(new URL('../src/components/CheckoutPage.jsx', import.meta.url), 'utf8')
const modalSrc = readFileSync(new URL('../src/components/CheckoutModal.jsx', import.meta.url), 'utf8')
assert(!checkoutSrc.includes('granted: true'), 'checkout lib never grants')
assert(pageSrc.includes('membershipReturnPaid'), 'checkout page only marks paid after Stripe return')
assert(!modalSrc.includes('addPremiumSub'), 'checkout modal does not fake a paid sub')
assert(pageSrc.includes('usePremiumCheckout'), 'checkout page uses shared premium hook')
assert(modalSrc.includes('usePremiumCheckout'), 'checkout modal uses shared premium hook')

const engagementSrc = readFileSync(new URL('../src/lib/engagement.js', import.meta.url), 'utf8')
assert(engagementSrc.includes('export const PREMIUM_PRICE = 5'), 'default list price')
assert(engagementSrc.includes('export function getMembershipPrice'), 'creator list price reader')
assert(engagementSrc.includes('export function setMembershipPrice'), 'creator can set list price')
assert(engagementSrc.includes('n >= 1 && n <= 50'), 'list price stays in range')
assert(engagementSrc.includes('pushFollow'), 'follows push to cloud')
assert(engagementSrc.includes('pushVote'), 'votes push to cloud')

const aboutSrc = readFileSync(new URL('../src/components/AboutPage.jsx', import.meta.url), 'utf8')
assert(aboutSrc.includes('Payouts are not live'), 'about does not promise payouts')
assert(aboutSrc.includes('Live video is not on yet'), 'about labels live honestly')

const authSrc = readFileSync(new URL('../src/components/AuthModal.jsx', import.meta.url), 'utf8')
assert(!authSrc.includes('Continue with Google'), 'google sign-in removed')
assert(authSrc.includes('Continue with Apple'), 'apple sign-in button')
assert(authSrc.includes('Continue with Microsoft'), 'microsoft sign-in button')
assert(authSrc.includes('Continue with X'), 'x sign-in button')
assert(authSrc.includes('loginWithOAuth'), 'oauth handler wired')
assert(authSrc.includes('Phone'), 'phone sign-in')
assert(!/supabase/i.test(authSrc), 'auth modal never says supabase')
assert(authSrc.includes('CapCut cannot sign people'), 'capcut is not a fake login')
assert(!authSrc.includes("&& synced &&"), 'oauth buttons show even when cloud auth is off')

const brandSrc = readFileSync(new URL('../src/lib/authBrand.js', import.meta.url), 'utf8')
assert(brandSrc.includes('Your Clips code is'), 'sms template says clips')
assert(brandSrc.includes('sanitizeAuthError'), 'auth errors are branded')

const secSrc = readFileSync(new URL('../src/components/settings/SecuritySettings.jsx', import.meta.url), 'utf8')
assert(secSrc.includes('startMfaEnroll'), 'real 2fa enroll')
assert(!secSrc.includes('Backend integration required'), '2fa is not a fake checkbox')

const shortsSrc = readFileSync(new URL('../src/components/ShortsFeed.jsx', import.meta.url), 'utf8')
assert(shortsSrc.includes('onStitch'), 'stitch on clip player')
assert(shortsSrc.includes('early_skip'), 'reel skip trains For You')
assert(!shortsSrc.includes('withReferenceShorts'), 'sample clips not mixed into feed')

const gridSrc = readFileSync(new URL('../src/components/ShortsGrid.jsx', import.meta.url), 'utf8')
assert(!gridSrc.includes('>Shorts<'), 'clips page has no Shorts title')
assert(gridSrc.includes('Recommended'), 'clips recommended tab')
assert(gridSrc.includes('Following'), 'clips following tab')
assert(!gridSrc.includes('Subscribed'), 'clips tab no longer says Subscribed')

const liveSrc = readFileSync(new URL('../src/components/LiveView.jsx', import.meta.url), 'utf8')
assert(liveSrc.includes('On now'), 'live page is homepage-style stream feed')
assert(liveSrc.includes('Go live from Create'), 'live page points go-live to Create (+)')
assert(!liveSrc.includes('Live lobby from the cloud'), 'live page dropped lobby chrome')
assert(!liveSrc.includes('Live channels'), 'live page has no Live channels heading')
assert(!liveSrc.includes('live-badge-glow'), 'no fake glowing LIVE badge')
assert(!liveSrc.includes('>Go live<') && !liveSrc.includes('Go live\n'), 'live tab has no Go live button')

const mig = readFileSync(new URL('../supabase/migrations/0006_social_graph.sql', import.meta.url), 'utf8')
assert(mig.includes('create table if not exists public.follows'), 'social graph migration')
const graphSrc = readFileSync(new URL('../src/lib/graphSync.js', import.meta.url), 'utf8')
assert(graphSrc.includes('export async function syncGraphFromCloud'), 'cloud graph pull')

const helpSrc = readFileSync(new URL('../src/components/HelpPage.jsx', import.meta.url), 'utf8')
assert(!/467 people/i.test(helpSrc), 'help does not mention named-account bots')
assert(!helpSrc.includes('Copy SQL'), 'help has no SQL copy buttons')
assert(!helpSrc.includes('Open SQL Editor'), 'help has no supabase editor')
assert(!helpSrc.includes('VITE_'), 'help has no env var names')
assert(helpSrc.includes('profile picture') || helpSrc.includes('profile menu'), 'help points studio to the profile menu')

const adminSetupSrc = readFileSync(new URL('../src/components/AdminSetup.jsx', import.meta.url), 'utf8')
assert(adminSetupSrc.includes('Copy'), 'admin setup has copy buttons')
assert(adminSetupSrc.includes('Open SQL Editor'), 'admin setup has a link to the sql editor')
assert(adminSetupSrc.includes('ORG.supabaseSqlEditor'), 'admin setup uses the supabase sql editor url')
assert(adminSetupSrc.includes('0009'), 'admin setup mentions 0009')

const settingsHub = readFileSync(new URL('../src/components/settings/SettingsHub.jsx', import.meta.url), 'utf8')
assert(settingsHub.includes('SecuritySettings'), 'settings hub includes real 2FA page')
assert(settingsHub.includes('RevenueSettings'), 'settings hub includes revenue dashboard')
const settingsTemplates = readFileSync(new URL('../src/components/settings/SettingsTemplates.jsx', import.meta.url), 'utf8')
assert(settingsTemplates.includes('SettingsPageHeader'), 'settings templates export page header')
assert(settingsTemplates.includes('SettingsKpiGrid'), 'settings templates export kpi grid')
const analyticsSet = readFileSync(new URL('../src/components/settings/AnalyticsSettings.jsx', import.meta.url), 'utf8')
assert(analyticsSet.includes('CreatorAnalyticsPanel'), 'analytics settings embeds shared panel')
const revenueSet = readFileSync(new URL('../src/components/settings/RevenueSettings.jsx', import.meta.url), 'utf8')
assert(revenueSet.includes('SettingsKpiGrid'), 'revenue settings use kpi template')
assert(revenueSet.includes('KICK_TWITCH_PARITY'), 'revenue settings show kick/twitch parity')
const settingsLayout = readFileSync(new URL('../src/components/settings/SettingsLayout.jsx', import.meta.url), 'utf8')
assert(settingsLayout.includes("'revenue'"), 'settings nav has revenue section')
const studioCatalog = readFileSync(new URL('../src/lib/creatorStudioCatalog.js', import.meta.url), 'utf8')
assert(studioCatalog.includes('CREATOR_STUDIO_GROUPS'), 'creator studio catalog defines nav groups')
assert(studioCatalog.includes('KICK_TWITCH_PARITY'), 'creator studio catalog tracks kick/twitch parity')
const errorReportsSrc = readFileSync(new URL('../src/lib/errorReports.js', import.meta.url), 'utf8')
assert(errorReportsSrc.includes('submitErrorReport'), 'error report helper exists')
const errorPromptSrc = readFileSync(new URL('../src/components/ErrorReportPrompt.jsx', import.meta.url), 'utf8')
assert(errorPromptSrc.includes('Report this error'), 'error report prompt exists')
const errorBoundarySrc = readFileSync(new URL('../src/components/ErrorBoundary.jsx', import.meta.url), 'utf8')
assert(errorBoundarySrc.includes('ErrorReportPrompt'), 'error boundary offers report')
const uploadModalSrc = readFileSync(new URL('../src/components/UploadModal.jsx', import.meta.url), 'utf8')
assert(uploadModalSrc.includes("Couldn't upload"), 'upload modal shows a clear failure message')
assert(errorBoundarySrc.includes('ErrorReportPrompt'), 'error boundary offers report (upload failures use boundary/report path)')
const dashStudioSrc = readFileSync(new URL('../src/components/studio/CreatorStudio.jsx', import.meta.url), 'utf8')
assert(dashStudioSrc.includes('InteractionBubbleMap'), 'creator studio has interaction bubble map')
assert(dashStudioSrc.includes('Your posts'), 'creator studio has posts column')
const appSrc = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
assert(appSrc.includes('SettingsHub'), 'settings layout is mounted')
assert(appSrc.includes('CreatorStudio'), 'creator studio shell is mounted')
const bubbleLib = readFileSync(new URL('../src/lib/creatorInteractions.js', import.meta.url), 'utf8')
assert(bubbleLib.includes('buildInteractionBubbles'), 'interaction bubbles are built from live events + tallies')
assert(bubbleLib.includes('skip'), 'bubble map tracks skips/kicks')
assert(bubbleLib.includes('surface'), 'bubble map stores where (surface)')
assert(bubbleLib.includes('mergeCreatorInteractionsFromCloud'), 'bubble map merges cloud events')
assert(bubbleLib.includes('notifyInteractionsChanged'), 'interaction log does not thrash catalog sync')
assert(!bubbleLib.includes("from './contentSync'"), 'creator interactions do not import contentSync notify')
assert(readFileSync(new URL('../src/lib/graphSync.js', import.meta.url), 'utf8').includes('pushCreatorInteraction'), 'graph sync pushes creator interactions')
assert(readFileSync(new URL('../supabase/migrations/0014_creator_interactions.sql', import.meta.url), 'utf8').includes('creator_interactions'), '0014 creates creator_interactions table')
assert(readFileSync(new URL('../src/components/PicsPage.jsx', import.meta.url), 'utf8').includes('once per opened pic'), 'pics view logging avoids refresh loops')
const settingsLayoutSrc = readFileSync(new URL('../src/components/settings/SettingsLayout.jsx', import.meta.url), 'utf8')
assert(settingsLayoutSrc.includes('SITE_SECTIONS'), 'site settings are separated')
assert(settingsLayoutSrc.includes('CREATOR_SECTIONS'), 'creator settings are separated')
assert(appSrc.includes('PasswordRecoveryGate'), 'reset-email landing exists')
assert(appSrc.includes("import MfaGate from './components/MfaGate'"), 'MfaGate is imported when MFA is pending')
assert(appSrc.includes('<MfaGate'), 'MfaGate mounts for pending MFA')
assert(!appSrc.includes("from './components/Navbar'"), 'legacy Navbar is not mounted')
assert(!appSrc.includes("from './components/Sidebar'"), 'legacy Sidebar is not mounted')
assert(!appSrc.includes('VideoPlayerModal'), 'watch uses WatchPage, not VideoPlayerModal')
const pkgJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))
assert(!pkgJson.dependencies?.['canvas-confetti'], 'canvas-confetti is not a runtime dependency')
assert(!pkgJson.devDependencies?.['puppeteer-core'], 'puppeteer-core is optional, not a default install')
assert(pkgJson.scripts?.knip, 'knip audit script exists')
assert(pkgJson.dependencies?.vite === undefined && pkgJson.devDependencies?.vite, 'vite stays a build tool')
assert(!pkgJson.dependencies?.webpack && !pkgJson.devDependencies?.webpack, 'no webpack')
assert(!pkgJson.dependencies?.lodash && !pkgJson.dependencies?.moment, 'no lodash or moment')
assert(!appSrc.includes("from './components/SettingsPage'"), 'old fake-2fa settings page is gone')
const moneySrc = readFileSync(new URL('../src/components/settings/MonetizationSettings.jsx', import.meta.url), 'utf8')
assert(!moneySrc.includes('100% of the listed price'), 'settings does not promise 100% payouts')
assert(!moneySrc.includes('Connect payout method'), 'no fake connect payout button')
assert(moneySrc.includes('SettingsPageHeader'), 'monetization settings use shared templates')
const streamSet = readFileSync(new URL('../src/components/settings/StreamSettings.jsx', import.meta.url), 'utf8')
assert(!streamSet.includes('rtmp://live.calabi'), 'no fake production rtmp url')
assert(streamSet.includes('Xbox') && streamSet.includes('PS5'), 'stream settings explain consoles')
assert(streamSet.includes('OBS') || streamSet.includes('ingest'), 'stream settings cover OBS/ingest')
assert(!streamSet.includes('cueLiveAd') && !streamSet.includes('snoozeLiveAds'), 'stream settings have no live ad controls')
const copySrc = readFileSync(new URL('../src/components/settings/CopyrightSettings.jsx', import.meta.url), 'utf8')
assert(copySrc.includes('copyright@calabi.us') || copySrc.includes('ORG.copyrightEmail'), 'dmca uses calabi.us')
assert(!copySrc.includes('platform.internal'), 'no internal placeholder emails')

const algoSrc = readFileSync(new URL('../src/lib/algorithmEngine.js', import.meta.url), 'utf8')
assert(algoSrc.includes('normalizeTaste'), 'taste profiles heal missing creator affinity maps')
assert(algoSrc.includes('creatorAffinity: { ...(raw.creatorAffinity || {}) }'), 'taste profiles default creator affinity')
assert(algoSrc.includes('explorationRoll'), 'for you exploration is session-stable')
assert(!algoSrc.includes('Math.random()'), 'ranker does not reshuffle every render')
const homeSrc = readFileSync(new URL('../src/components/HomeFeed.jsx', import.meta.url), 'utf8')
assert(homeSrc.includes('getStableHomeFeed'), 'home recommended is frozen until refresh')
assert(homeSrc.includes('useContentSyncTick'), 'home refreshes after cloud catalog sync')
assert(homeSrc.includes('isCatalogHydrated'), 'home waits for catalog hydration before empty state')
assert(homeSrc.includes('Loading posts'), 'home shows loading instead of false empty state')
assert(homeSrc.includes('syncContentFromCloud'), 'home kicks catalog sync on mount')
assert(homeSrc.includes('FilterChips'), 'home has All/Videos/Clips/Pics filter chips')
assert(homeSrc.includes("label: 'All'"), 'home defines All filter label')
assert(homeSrc.includes("label: 'Pics'") || homeSrc.includes("label: 'Clips'"), 'home has type filter chips')
assert(readFileSync(new URL('../app/SpaShell.jsx', import.meta.url), 'utf8').includes('syncContentFromCloud'), 'SpaShell pulls catalog on boot')
assert(readFileSync(new URL('../src/lib/catalogStore.js', import.meta.url), 'utf8').includes('markCatalogHydrated'), 'catalog can mark hydrated after empty pull')
const shortsFeedSrc = readFileSync(new URL('../src/components/ShortsFeed.jsx', import.meta.url), 'utf8')
assert(shortsFeedSrc.includes('getStableShortsFeed'), 'clips recommended is frozen until refresh')
assert(shortsFeedSrc.includes('el.currentTime >= 1'), 'clips count views after playback starts')
assert(shortsFeedSrc.includes('getWatchItem(focusId)'), 'clips from a profile still open that clip')
assert(shortsFeedSrc.includes('getCreatorPublicContent'), 'channel clip opens that creator reel not a random global feed')
const stageSrc = readFileSync(new URL('../src/components/ShortsStage.jsx', import.meta.url), 'utf8')
assert(stageSrc.includes('loop = true') || stageSrc.includes('loop ?? true'), 'clips and pics loop endlessly')
assert(stageSrc.includes('copies = loop && n > 0 ? 3 : 1'), 'loop uses a triple buffer for seamless wrap')
assert(stageSrc.includes('snap-always'), 'clip slides always snap fully into view')
assert(stageSrc.includes('lastCount'), 'clip stage realigns when slide count changes')
const storageSrc = readFileSync(new URL('../src/lib/storage.js', import.meta.url), 'utf8')
assert(storageSrc.includes('catalogStore') || storageSrc.includes('getCatalog'), 'catalog reads come from in-memory catalogStore')
assert(storageSrc.includes('setCatalog') || storageSrc.includes('replaceImportsFromCloud') || storageSrc.includes("from './catalogStore'"), 'cloud pulls replace session catalog')
assert(!storageSrc.includes('.slice(0, 200)'), 'saveImport no longer hard-slices to 200')
const seedSrc = readFileSync(new URL('../src/data/publicMediaSeed.js', import.meta.url), 'utf8')
assert(seedSrc.includes('mergeImports(batch)'), 'catalog seed uses one protected merge')
assert(!/saveImport\(record\)/.test(seedSrc), 'catalog seed does not loop saveImport')
const healthSrcUpload = readFileSync(new URL('../src/lib/catalogHealth.js', import.meta.url), 'utf8')
assert(healthSrcUpload.includes('isUserUploadRecord'), 'catalog health knows user uploads')
assert(healthSrcUpload.includes('isFeedable'), 'catalog health has feedable gate')
assert(healthSrcUpload.includes('localStored === true'), 'empty-media uploads are not treated as playable')
assert(healthSrcUpload.includes('isHttpUrl'), 'shared feeds require public URLs for user uploads')
const cardProtect = readFileSync(new URL('../src/components/ContentCard.jsx', import.meta.url), 'utf8')
assert(cardProtect.includes('isUserUploadRecord'), 'cards do not delete user uploads on thumb error')
const publishSrc = readFileSync(new URL('../src/lib/contentService.js', import.meta.url), 'utf8')
assert(publishSrc.includes('resolveUploadHost'), 'video publish requires a host session')
assert(publishSrc.includes('pushContentRecord'), 'video publish waits on catalog when hosted')
assert(publishSrc.includes('deleteHostedMedia'), 'delete removes hosted storage objects')
assert(!publishSrc.includes('storeMediaBlob'), 'video publish never keeps empty device-only posts')
assert(publishSrc.includes('localStored: raw.localStored === true'), 'normalize keeps localStored for playback')
assert(publishSrc.includes('signInToUploadMessage') || publishSrc.includes('Sign in to upload'), 'upload asks to sign in plainly')
const picsPublishSrc = readFileSync(new URL('../src/lib/picsService.js', import.meta.url), 'utf8')
assert(picsPublishSrc.includes('resolveUploadHost'), 'photo publish requires a host session')
assert(!picsPublishSrc.includes('storeMediaBlob'), 'photo publish never keeps empty device-only posts')
const mediaUpSrc = readFileSync(new URL('../src/lib/mediaUpload.js', import.meta.url), 'utf8')
assert(mediaUpSrc.includes('export function canHostUploads'), 'canHostUploads helper exists')
assert(mediaUpSrc.includes('resolveUploadHost'), 'resolveUploadHost picks live session for uploads')
assert(mediaUpSrc.includes('deleteHostedMedia'), 'hosted media can be deleted from the bucket')
assert(mediaUpSrc.includes('signInToUploadMessage'), 'plain sign-in copy for uploads')
assert(!mediaUpSrc.includes('Clips cloud account'), 'upload errors do not say Clips cloud')
const uploadSrcEarly = readFileSync(new URL('../src/components/UploadModal.jsx', import.meta.url), 'utf8')
assert(!uploadSrcEarly.includes('canHostUploads'), 'upload modal does not lecture about hosting')
assert(!uploadSrcEarly.includes('source of truth'), 'upload modal has no infra jargon')
assert(!uploadSrcEarly.includes('storeMediaBlob'), 'upload modal does not stash draft files in IndexedDB')
assert(uploadSrcEarly.includes('Publish') || uploadSrcEarly.includes('Uploading'), 'upload modal has publish/upload CTA')
assert(uploadSrcEarly.includes("Couldn't upload") || uploadSrcEarly.includes('Uploading'), 'upload modal reports progress/errors')
assert(!uploadSrcEarly.includes('Live shared link'), 'upload popup does not say Live shared link')
const shortsFeedSrcScroll = readFileSync(new URL('../src/components/ShortsFeed.jsx', import.meta.url), 'utf8')
assert(shortsFeedSrcScroll.includes('key="clips-reel"'), 'clip player stays mounted across scroll')
assert(!shortsFeedSrcScroll.includes('key={`clips-player-${focusId'), 'clip player does not remount per clip id')
assert(shortsFeedSrcScroll.includes('Land on a real clip URL'), 'clips tab opens straight into a clip reel')
assert(shortsFeedSrcScroll.includes('replaceHash'), 'clip scroll soft-updates the share URL')
assert(!shortsFeedSrcScroll.includes('ShortsGrid'), 'clips tab skips the recommended grid gate')
assert(shortsFeedSrcScroll.includes('touch-pan-y'), 'clip tap layer allows vertical swipe')
assert(shortsFeedSrcScroll.includes('isFeedable'), 'clip reel skips ghost uploads')
assert(!shortsFeedSrcScroll.includes('mixFeedAds'), 'clip reel does not mix ad slides')
const stageSrcScroll = readFileSync(new URL('../src/components/ShortsStage.jsx', import.meta.url), 'utf8')
assert(stageSrcScroll.includes('touch-pan-y'), 'clip scroller allows vertical swipe')
assert(stageSrcScroll.includes('lastCount'), 'clip stage realigns when slide count changes')

const restoreSrc = readFileSync(new URL('../src/lib/restoreUploads.js', import.meta.url), 'utf8')
assert(restoreSrc.includes('export async function restoreLostUploads'), 'restoreLostUploads is exported')
assert(restoreSrc.includes('listMediaBlobIds'), 'restore rebuilds catalog from IndexedDB')
assert(restoreSrc.includes('user_clips'), 'restore reads legacy user_clips')
const mainSrc = readFileSync(new URL('../src/main.jsx', import.meta.url), 'utf8')
assert(mainSrc.includes('restoreLostUploads'), 'boot runs restoreLostUploads')
const studioSrc = readFileSync(new URL('../src/components/studio/CreatorStudio.jsx', import.meta.url), 'utf8')
assert(studioSrc.includes('Make a post'), 'Creator Studio has Make a post in Calabi Studio')
assert(studioSrc.includes('Controls'), 'Creator Studio has Controls tab')
assert(!studioSrc.includes('> Import') && !studioSrc.includes('Import</'), 'Creator Studio has no Import control')
assert(!studioSrc.includes('title="Restore missing posts"'), 'Creator Studio has no Restore control')
assert(!studioSrc.includes("onClick={() => onNavigate?.('live')}"), 'Creator Studio header has no Live button')
assert(!studioSrc.includes('restoreLostUploads'), 'Creator Studio no longer surfaces restore')
assert(studioSrc.includes('listMediaBlobIds') === false, 'studio uses restore helper not raw IDB')
assert(studioSrc.includes("id: 'lab'") && studioSrc.includes('Calabi Studio'), 'Creator Studio has Calabi Studio section')
assert(!studioSrc.includes("id: 'post'"), 'Make a post is merged into Calabi Studio')
assert(studioSrc.includes("id: 'lab'") && studioSrc.includes('labTool'), 'Creator Studio folds controls into Calabi Studio')
assert(studioSrc.includes("id: 'content'"), 'Creator Studio has content section')
assert(studioSrc.includes('SettingsKpiGrid'), 'analytics KPIs stay on SettingsKpiGrid')
assert(!/section === 'overview'[\s\S]{0,800}SettingsKpiGrid/.test(studioSrc), 'overview no longer shows KPI strip')
const videoStoreSrc = readFileSync(new URL('../src/lib/videoStorage.js', import.meta.url), 'utf8')
assert(videoStoreSrc.includes('export async function listMediaBlobIds'), 'IndexedDB can list media ids for restore')
assert(videoStoreSrc.includes('export async function deleteMediaBlob'), 'device blobs can be removed after cloud promote')
const promoteSrc = readFileSync(new URL('../src/lib/promoteUploads.js', import.meta.url), 'utf8')
assert(promoteSrc.includes('promoteDeviceUploadsToCloud'), 'legacy device uploads can be promoted to cloud links')
assert(promoteSrc.includes('resolveUploadHost'), 'promote uses the live host session')
const appPromoteSrc = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
assert(appPromoteSrc.includes('promoteDeviceUploadsToCloud'), 'signed-in sessions promote device uploads to cloud')
assert(appPromoteSrc.includes('subscribeCloudCatalog'), 'app listens for other people\'s new uploads')
const syncSrcLive = readFileSync(new URL('../src/lib/contentSync.js', import.meta.url), 'utf8')
assert(syncSrcLive.includes('subscribeCloudCatalog'), 'cloud catalog live subscription exists')
assert(syncSrcLive.includes('postgres_changes'), 'live subscription uses catalog change events')

assert(!storageSrc.includes('next.createdAt = now'), 'library merge does not bump timestamps to now')
const preloadSrc = readFileSync(new URL('../src/lib/preloadMedia.js', import.meta.url), 'utf8')
assert(preloadSrc.includes('export function preloadPostedItem'), 'next posts can warm in the background')
const watchSrcPre = readFileSync(new URL('../src/components/WatchPage.jsx', import.meta.url), 'utf8')
assert(watchSrcPre.includes('countViewOnProgress'), 'watch counts a view after real playback')
assert(watchSrcPre.includes('getWatchItem'), 'watch resolves items from click stash')
assert(watchSrcPre.includes('currentTime < 1'), 'watch waits for at least one second of playback')
const cardSrc = readFileSync(new URL('../src/components/ContentCard.jsx', import.meta.url), 'utf8')
assert(cardSrc.includes('onOpenProfile'), 'cards accept an explicit profile opener')
assert(cardSrc.includes('openProfile') && cardSrc.includes('onClick={open}'), 'video thumb and title play — only avatar and name open profile')
// Ads removed from product surfaces — keep only no-op stubs + non-ad product asserts
assert(!existsSync(new URL('../src/lib/exoClickServe.js', import.meta.url)), 'exoClickServe module removed')
assert(!existsSync(new URL('../src/lib/adZones.js', import.meta.url)), 'adZones module removed')
assert(!existsSync(new URL('../src/lib/feedAdCadence.js', import.meta.url)), 'feedAdCadence module removed')
assert(!existsSync(new URL('../src/components/ExoClickDisplay.jsx', import.meta.url)), 'ExoClickDisplay removed')
assert(!existsSync(new URL('../src/components/AdminAds.jsx', import.meta.url)), 'AdminAds removed')
assert(!existsSync(new URL('../src/components/AdUnits.jsx', import.meta.url)), 'AdUnits removed')
assert(!shortsFeedSrc.includes('mixFeedAds') && !shortsFeedSrc.includes('InFeedAd'), 'clip reel has no ad mixer')
assert(!shortsFeedSrc.includes('ClipFeedAdSlide'), 'clip reel has no sponsored slides')
const adsSrc = readFileSync(new URL('../src/components/AdvertisePage.jsx', import.meta.url), 'utf8')
assert(!adsSrc.includes('90%'), 'advertise page does not invent a 90% rev share')
assert(!adsSrc.includes('within 24 hours'), 'advertise page does not promise 24 hour approval')
assert(/don.t sell ad inventory|No ad network|FEATURE_ADS/i.test(adsSrc), 'advertise page is honesty shell for no-ads product')
assert(!adsSrc.includes('in-stream ad 30 seconds'), 'advertise page does not sell in-stream inventory')
const flagsSrc = readFileSync(new URL('../src/lib/featureFlags.js', import.meta.url), 'utf8')
assert(flagsSrc.includes('FEATURE_ADS = false'), 'FEATURE_ADS defaults false')
const portalSrc = readFileSync(new URL('../src/components/AdvertiserPortal.jsx', import.meta.url), 'utf8')
assert(portalSrc.includes('Ads are not offered') || portalSrc.includes('adsEnabled'), 'advertiser portal cannot run campaigns')
const applySrc = readFileSync(new URL('../src/components/CreatorApplyPage.jsx', import.meta.url), 'utf8')
assert(applySrc.includes('What is not live'), 'creator apply lists what is not shipped')
assert(applySrc.includes('CONTENT_RULES_SHORT'), 'creator apply shows content rules')
assert(applySrc.includes('Ad RPM') || applySrc.includes('not live'), 'creator apply says ad RPM is not live')
const adEng = readFileSync(new URL('../src/lib/adEngine.js', import.meta.url), 'utf8')
assert(adEng.includes('getAdSenseClientId') || adEng.includes('ADSENSE_KEEP_STREAM_PIP') || adEng.includes('Ads removed'), 'adEngine stays thin stub')
assert(adEng.includes('mixFeedAds'), 'adEngine still exports mixFeedAds passthrough')
assert(!readFileSync(new URL('../app/layout.jsx', import.meta.url), 'utf8').includes('adsenseClientId'), 'App Router layout has no AdSense client script')
assert(existsSync(new URL('../app/api/health/route.js', import.meta.url)), 'health API route exists')
assert(readFileSync(new URL('../app/SpaShell.jsx', import.meta.url), 'utf8').includes('Skip to content'), 'SpaShell has skip-to-content')
assert(readFileSync(new URL('../src/index.css', import.meta.url), 'utf8').includes('prefers-reduced-motion'), 'reduced motion CSS present')
const catalogLabels = readFileSync(new URL('../src/lib/creatorStudioCatalog.js', import.meta.url), 'utf8')
assert(catalogLabels.includes("label: 'Coins'"), 'studio catalog says Coins')
assert(!catalogLabels.includes('Wallet & Cash'), 'studio catalog dropped Wallet & Cash')
const videoStorageSrc = readFileSync(new URL('../src/lib/videoStorage.js', import.meta.url), 'utf8')
assert(videoStorageSrc.includes('original file') || videoStorageSrc.includes('no browser'), 'uploads keep original file — no forced WebM re-encode')
const tipsClaim = readFileSync(new URL('../src/lib/tips.js', import.meta.url), 'utf8')
assert(tipsClaim.includes('alreadyClaimed') || tipsClaim.includes('calabi_stripe_claimed_'), 'Stripe return claim is idempotent')
const helpSrc500 = readFileSync(new URL('../src/components/HelpPage.jsx', import.meta.url), 'utf8')
assert(helpSrc500.includes('Coins') && (helpSrc500.includes('Orders') || helpSrc500.includes('Orders tab')), 'Help documents Coins/Orders')
assert(helpSrc500.includes('RTMP') || helpSrc500.includes('lobby'), 'Help documents lobby vs RTMP')
const dashSrc2 = readFileSync(new URL('../src/components/studio/CreatorStudio.jsx', import.meta.url), 'utf8')
assert(dashSrc2.includes('Apply to earn'), 'creator studio offers apply to earn')
assert(dashSrc2.includes('Earn approved') || dashSrc2.includes('approved'), 'creator studio shows earn status')
assert(!/grid-cols-4[\s\S]{0,400}\$\{b\.paid/.test(dashSrc2), 'creator dashboard overview has no dollar tile')
const ledgerSrc = readFileSync(new URL('../src/lib/financialLedger.js', import.meta.url), 'utf8')
assert(!ledgerSrc.includes('calculateAdRevenueSplit'), 'there is no creator ad revenue split')
assert(!ledgerSrc.includes('estimatedAdRevenue'), 'wallets do not estimate ad revenue')
const monSrc = readFileSync(new URL('../src/components/settings/MonetizationSettings.jsx', import.meta.url), 'utf8')
assert(monSrc.includes('not a creator share') || monSrc.includes('Payouts'), 'monetization stays honest about ads/payouts')
const shelvesSrc2 = readFileSync(new URL('../src/components/MediaShelves.jsx', import.meta.url), 'utf8')
assert(!shelvesSrc2.includes('mixFeedAds') && !shelvesSrc2.includes('InFeedAd'), 'home and profile shelves have no recommended-grid ads')
const watchSrc3 = readFileSync(new URL('../src/components/WatchPage.jsx', import.meta.url), 'utf8')
assert(!watchSrc3.includes('useVideoVastAds'), 'watch page has no VAST hook')
assert(!watchSrc3.includes('VideoInStreamAd'), 'watch page has no in-stream ad overlay')
assert(!watchSrc3.includes('ExoClickDisplay'), 'watch page has no display unit under the video')
const picsPageSrc = readFileSync(new URL('../src/components/PicsPage.jsx', import.meta.url), 'utf8')
assert(!picsPageSrc.includes('mixFeedAds') && !picsPageSrc.includes('InFeedAd'), 'pic viewer has no scroll ads')
assert(!picsPageSrc.includes('PicFeedAdSlide'), 'pic reel has no sponsored slides')
const paySrc = readFileSync(new URL('../src/lib/payouts.js', import.meta.url), 'utf8')
assert(!paySrc.includes('rpmPerThousand'), 'payouts are not a per-1000-views rate')
assert(!paySrc.includes('DEFAULT_RPM'), 'no default view rpm')
assert(paySrc.includes('recordManualPayout'), 'admin can mark a hand payout sent')
assert(applySrc.includes('Apply to earn'), 'apply page is for earning not posting')
const adminSrc = readFileSync(new URL('../src/components/AdminPortal.jsx', import.meta.url), 'utf8')
assert(adminSrc.includes("id: 'payouts'"), 'admin has a payouts tab')
assert(adminSrc.includes("id: 'setup'"), 'admin has a setup tab for sql')
assert(adminSrc.includes("id: 'people'"), 'admin has a people workspace')
assert(adminSrc.includes('AdminSetup'), 'admin setup is not on Help')
assert(!adminSrc.includes('AdminAds'), 'admin ads tab is gone')
assert(adminSrc.includes('AdminPeople'), 'admin people table is editable')
assert(adminSrc.includes('Cloud password'), 'admin unlock asks for cloud password')
assert(adminSrc.includes('password: pass'), 'admin unlock passes cloud password into login')
assert(adminSrc.includes('kiddnixk@gmail.com'), 'admin unlock hints owner email')
assert(adminSrc.includes('Signing in'), 'admin unlock shows busy state')
assert(adminSrc.includes('onSubmit={onUnlock}'), 'admin unlock is a real form submit')
assert(adminSrc.includes('ADMIN_UNLOCK_KEY'), 'admin unlock persists across remounts')
const authBodySrc = readFileSync(new URL('../src/context/AuthContextBody.jsx', import.meta.url), 'utf8')
assert(authBodySrc.includes('Do not await cloud sync here'), 'owner login does not hang unlock on sync')
const moderationSrc = readFileSync(new URL('../src/lib/moderation.js', import.meta.url), 'utf8')
assert(moderationSrc.includes("PLATFORM_OWNER_HANDLE = 'kiddnixk'"), 'platform owner handle is kiddnixk')
assert(/isAdminSession[\s\S]*return true/.test(moderationSrc), 'admin session returns true when unlocked')
const trustSrc = readFileSync(new URL('../src/lib/trustSafety.js', import.meta.url), 'utf8')
assert(trustSrc.includes('export function banUser'), 'admin can ban people')
assert(trustSrc.includes('export function suspendUser'), 'admin can suspend people')
assert(trustSrc.includes('export function holdPayouts'), 'admin can hold payouts')
assert(trustSrc.includes('export function adminUpdateProfile'), 'admin can edit profiles')
assert(trustSrc.includes('export function addStrike'), 'admin can issue youtube-style strikes')
const shortsGridSrc = readFileSync(new URL('../src/components/ShortsGrid.jsx', import.meta.url), 'utf8')
assert(!shortsGridSrc.includes('mixFeedAds') && !shortsGridSrc.includes('InFeedAd'), 'clip Recommended grid has no ads')
const picsSrc = readFileSync(new URL('../src/components/PicsPage.jsx', import.meta.url), 'utf8')
assert(picsSrc.includes('togglePicHeart'), 'pics can be hearted')
assert(picsSrc.includes('PicHeartBtn'), 'pic viewer shows heart only on the active slide')
const watchAgainSrc = readFileSync(new URL('../src/components/WatchAgainPage.jsx', import.meta.url), 'utf8')
assert(watchAgainSrc.includes('listWatchAgain'), 'watch again tab lists finished videos')
const heartsSrc = readFileSync(new URL('../src/components/HeartsPage.jsx', import.meta.url), 'utf8')
assert(heartsSrc.includes('getPicHearts'), 'hearts tab lists hearted pics')
assert(!picsSrc.includes('ExoClickDisplay'), 'pic viewer does not play an ad over the photo')
const dashSrc = readFileSync(new URL('../src/components/studio/CreatorStudio.jsx', import.meta.url), 'utf8')
assert(dashSrc.includes("id: 'earnings'"), 'creator studio has earnings section')
assert(dashSrc.includes("id: 'content'"), 'creator studio has content section for vods/videos/pics/clips/news')
assert(dashSrc.includes('Creator settings'), 'studio gear opens creator settings')
assert(dashSrc.includes("id: 'lab'") && dashSrc.includes('labTool'), 'studio has Calabi Studio with controls/stream tools')
assert(!dashSrc.includes("id: 'post'"), 'Make a post merged into Calabi Studio nav')
assert(dashSrc.includes('Channel stats') || dashSrc.includes('SettingsKpiGrid'), 'analytics holds channel KPIs')
const vodLib = readFileSync(new URL('../src/lib/vods.js', import.meta.url), 'utf8')
assert(vodLib.includes('archiveEndedLive'), 'ended lives are copied')
assert(vodLib.includes('setVodChannel'), 'creators can enable a VOD channel')
const ownerSrc = readFileSync(new URL('../src/data/ownerLogin.js', import.meta.url), 'utf8')
assert(ownerSrc.includes('kiddnixk@gmail.com'), 'owner preferred cloud email is kiddnixk@gmail.com')
assert(ownerSrc.includes('ownerCloudEmails'), 'owner aliases resolve to cloud emails')
assert(ownerSrc.includes('cs1@calabi.us'), 'legacy cs1@calabi.us still tried for Auth')
assert(!!findOwnerLogin('kiddnixk'), 'owner sign-in accepts handle kiddnixk')
assert(!!findOwnerLogin('kiddnixk@gmail.com'), 'owner sign-in accepts kiddnixk gmail')
assert(!!findOwnerLogin('cs1'), 'legacy cs1 alias still maps to owner')
assert(!!findOwnerLogin('cs1@calabi.us'), 'legacy cs1 email still maps to owner')
assert(!isLocalOwnerLogin('kiddnixk'), 'owner has no local-only alias path')
assert(!findOwnerLogin('name1@calabi.com'), 'named accounts are not owner')
{
  const mails = ownerCloudEmails('kiddnixk')
  assert(mails.includes('kiddnixk@gmail.com'), 'kiddnixk handle maps to cloud email')
  assert(mails.includes('cs1@calabi.us'), 'owner login also tries legacy cloud email')
  assert(!mails.some((e) => e.endsWith('.local')), 'owner cloud emails never use .local')
}
const authOwnerSrc = readFileSync(new URL('../src/context/AuthContextBody.jsx', import.meta.url), 'utf8')
assert(authOwnerSrc.includes('ownerCloudEmails'), 'owner login uses cloud email list')
assert(authOwnerSrc.includes("provider: 'supabase'"), 'owner session is supabase provider')
assert(!authOwnerSrc.includes("provider: 'local',\n          avatarUrl: '',\n          bannerUrl: '',\n          bio: '',\n          passwordHash: owner.passwordHash"), 'owner has no local owner session fallback')
assert(authOwnerSrc.includes('Cloud sign-in is required for the owner account'), 'owner requires cloud when supabase missing')
assert(authOwnerSrc.includes('resetPasswordForEmail'), 'owner can use cloud password reset')
assert(!/signUp\(\{[\s\S]{0,80}owner\.displayName/.test(authOwnerSrc), 'owner login does not auto-signUp as owner')
function ownerHashMatches(raw, stored) {
  const parts = String(stored || '').split('$')
  if (parts.length < 3) return false
  const next = createHash('sha256').update(`${parts[1]}:${raw}`).digest('hex')
  return next === parts[2]
}
const ownerHashes = [OWNER_LOGIN.passwordHash, ...(OWNER_LOGIN.passwordHashes || [])]
assert(ownerHashes.some((h) => ownerHashMatches('cs1cs1', h)), 'admin portal still has owner password hashes')
const liveAdsSrc = readFileSync(new URL('../src/lib/liveAds.js', import.meta.url), 'utf8')
assert(liveAdsSrc.includes('Ads removed') || liveAdsSrc.includes('cueLiveAd'), 'liveAds is a stub module')
assert(liveAdsSrc.includes('LIVE_VIEWER_AD_DELAY_SEC = 0') || liveAdsSrc.includes('return { ok: false'), 'live viewer ads are disabled')
assert(!readFileSync(new URL('../src/components/LiveView.jsx', import.meta.url), 'utf8').includes('Snooze ads'), 'live host UI has no ad controls')

const creatorsSrc = readFileSync(new URL('../src/components/CreatorsPage.jsx', import.meta.url), 'utf8')
assert(creatorsSrc.includes('listSidebarCreators'), 'creators page ranks people who posted')

const healthSrc = readFileSync(new URL('../src/lib/catalogHealth.js', import.meta.url), 'utf8')
assert(healthSrc.includes('purgeDeadCatalog'), 'dead pics and sample clips are purged')
assert(healthSrc.includes('isUserUploadRecord'), 'catalog health protects user uploads')
assert(healthSrc.includes('hosted === true') || healthSrc.includes('row.hosted'), 'hideBrokenMedia keeps hosted uploads')
const picsWipe = readFileSync(new URL('../src/components/PicsPage.jsx', import.meta.url), 'utf8')
assert(!/dropBroken[\s\S]{0,200}deleteCatalogItem/.test(picsWipe), 'pics media errors must not cloud-delete posts')
assert(picsWipe.includes('hideBrokenMedia'), 'pics still hides broken tiles locally')
assert(readFileSync(new URL('../src/lib/contentSync.js', import.meta.url), 'utf8').includes('unhideBrokenMedia'), 'cloud sync clears false broken hides')

const purgeSql = readFileSync(new URL('../supabase/migrations/0007_purge_dead_media.sql', import.meta.url), 'utf8')
assert(purgeSql.includes("type = 'pic'"), 'sql removes unplayable pics')

const purgeSql8 = readFileSync(new URL('../supabase/migrations/0008_purge_dead_media.sql', import.meta.url), 'utf8')
assert(purgeSql8.includes('picsum'), 'sql 0008 removes leftover sample hosts')

const profileMedia = readFileSync(new URL('../src/lib/profileMedia.js', import.meta.url), 'utf8')
assert(profileMedia.includes('persistProfilePicture'), 'profile photos persist outside localStorage quota')
const channelSrc = readFileSync(new URL('../src/components/ChannelPage.jsx', import.meta.url), 'utf8')
assert(channelSrc.includes('Saved as you type'), 'channel saves while you type')
assert(channelSrc.includes('Change profile picture'), 'avatar camera is on the photo')

assert(cardSrc.includes('PostedStamp'), 'home cards show real post time')
assert(cardSrc.includes('viewsLabel'), 'cards format view counts')
assert(cardSrc.includes('Download'), 'cards can download a post')
assert(cardSrc.includes('VerifiedBadge'), 'cards put the checkmark beside the name')
assert(!cardSrc.includes('official={official}'), 'cards do not put the checkmark on the avatar')
const watchSrc2 = readFileSync(new URL('../src/components/WatchPage.jsx', import.meta.url), 'utf8')
assert(watchSrc2.includes('downloadPostedMedia'), 'watch page can download')
const dlSrc = readFileSync(new URL('../src/lib/mediaDownload.js', import.meta.url), 'utf8')
assert(dlSrc.includes('Anyone can save'), 'downloads are public')
const vidStore = readFileSync(new URL('../src/lib/videoStorage.js', import.meta.url), 'utf8')
assert(vidStore.includes('transcodeVideoForUpload'), 'uploads are transcoded for space')
const pubSrc = readFileSync(new URL('../src/lib/contentService.js', import.meta.url), 'utf8')
assert(pubSrc.includes('transcodeVideoForUpload'), 'publish path uses the transcode')
assert(pubSrc.includes('isRetiredCatalogItem(fromImport)'), 'watch can open a profile video that is not in the home feed filter')
assert(pubSrc.includes('getWatchItem'), 'watch item resolver tolerates stale feed entries')
assert(pubSrc.includes('stashWatchItem'), 'clicked items are remembered for playback')
const navSrc = readFileSync(new URL('../src/components/StreamingNavbar.jsx', import.meta.url), 'utf8')
assert(!navSrc.includes('SiteClock'), 'header does not show a site clock')
assert(!navSrc.includes('withWord'), 'header shows logo only without calabi wordmark')
assert(!navSrc.includes('onToggleSidebar'), 'header has no sidebar toggle')
assert(!navSrc.includes('<Menu'), 'header has no hamburger icon')
assert(!navSrc.includes('handleNav(\'live\')'), 'header does not show Live Recommended Explore Clips')
assert(!/\bRecommended\b/.test(navSrc) && !/\bExplore\b/.test(navSrc) && !/\bClips\b/.test(navSrc), 'header has no Recommended Live Explore Clips chips')
const sideSrc = readFileSync(new URL('../src/components/CollapsibleSidebar.jsx', import.meta.url), 'utf8')
assert(sideSrc.includes('Top creators'), 'sidebar heading is Top creators')
assert(sideSrc.includes('label="Following"'), 'sidebar following tab')
assert(sideSrc.includes('label="API"') && sideSrc.includes("go('api')"), 'sidebar More has API tab')
assert(!sideSrc.includes('label="Subscribed"'), 'sidebar no longer says Subscribed')
assert(!sideSrc.includes('Creator Dashboard'), 'sidebar has no creator dashboard')
assert(!sideSrc.includes('label="Wallet"'), 'sidebar has no wallet')
assert(!sideSrc.includes('label="Analytics"'), 'sidebar has no analytics')
assert(!sideSrc.includes('Apply to create'), 'sidebar has no creator application')
assert(navSrc.includes('Creator dashboard'), 'profile menu has creator dashboard')
assert(navSrc.includes('Messages'), 'profile menu has Messages')
const profilePageMenu = readFileSync(new URL('../src/components/ProfilePage.jsx', import.meta.url), 'utf8')
assert(profilePageMenu.includes('Message'), 'profile page has Message button')
const dmLib = readFileSync(new URL('../src/lib/directMessages.js', import.meta.url), 'utf8')
assert(dmLib.includes('sanitizeDmBody') && dmLib.includes('openDmThread'), 'secure DM lib exists')
assert(dmLib.includes('Cloud sign-in required'), 'DMs require cloud sign-in')
assert(existsSync(new URL('../supabase/migrations/0022_direct_messages.sql', import.meta.url)), 'DM migration 0022 exists')
const dmMig = readFileSync(new URL('../supabase/migrations/0022_direct_messages.sql', import.meta.url), 'utf8')
assert(dmMig.includes('row level security') && dmMig.includes('dm_messages'), 'DM tables use RLS')
assert(existsSync(new URL('../app/messages/page.jsx', import.meta.url)), 'messages route exists')
assert(readFileSync(new URL('../app/robots.js', import.meta.url), 'utf8').includes('/messages'), 'robots disallows messages')
assert(!navSrc.includes('> Analytics'), 'profile menu has no analytics')
assert(navSrc.includes('Site settings'), 'profile menu has site settings')
assert(!navSrc.includes('Account settings'), 'profile menu no longer says Account settings')
assert(!navSrc.includes('> Settings</'), 'profile menu no longer uses generic Settings label')
const analyticsSrc = readFileSync(new URL('../src/components/AnalyticsPage.jsx', import.meta.url), 'utf8')
const analyticsPanel = readFileSync(new URL('../src/components/settings/CreatorAnalyticsPanel.jsx', import.meta.url), 'utf8')
assert(analyticsSrc.includes('CreatorAnalyticsPanel'), 'analytics page uses shared panel template')
assert(analyticsPanel.includes('Overview'), 'creator analytics has an overview portal')
assert(analyticsPanel.includes('Reach by post'), 'creator analytics charts real post views')
assert(analyticsPanel.includes('SettingsTable'), 'creator analytics has a posts table template')
assert(!/youtube|studio.google|impressions ctr/i.test(analyticsPanel), 'creator analytics is not a YouTube Studio clone')
const engAnalytics = readFileSync(new URL('../src/lib/engagement.js', import.meta.url), 'utf8')
assert(engAnalytics.includes('listCreatorAnalyticsRows'), 'analytics rows come from posted content')
assert(!navSrc.includes('> Wallet</'), 'profile menu has no bare Wallet item')
assert(navSrc.includes('> Coins') || navSrc.includes('Coins'), 'profile menu opens Coins')
assert(!navSrc.includes('Your Coins'), 'profile menu says Coins not Your Coins')
assert(navSrc.includes('Orders'), 'profile menu has Orders under Coins')
assert(!navSrc.includes('> VODs'), 'profile menu has no vods')
assert(!navSrc.includes('Get verified'), 'profile menu has no get verified')
assert(!navSrc.includes('> Channel'), 'profile menu has no channel')
assert(!navSrc.includes('Creator Studio'), 'profile menu uses Creator dashboard label')
assert(sideSrc.includes('min-h-0 overflow-y-auto'), 'sidebar still scrolls')
assert(sideSrc.includes('label="Create"'), 'sidebar has Create')
assert(sideSrc.includes('label="Following"'), 'sidebar following under Create')
assert(sideSrc.includes('Following sits under Create'), 'Following is separated under Create')
assert(sideSrc.includes('label="Watch again"'), 'sidebar has watch again tab')
assert(sideSrc.includes('label="Hearts"'), 'sidebar has hearts tab for pics')
assert(!sideSrc.includes('label="Notifications"'), 'notifications are not a sidebar tab')
assert(sideSrc.includes('w-14') && (sideSrc.includes("collapsed ? 'w-14' : 'w-60'") || sideSrc.includes("collapsed = true")), 'sidebar keeps an icon rail when collapsed')
assert(sideSrc.includes('ChannelAvatar') && sideSrc.includes('collapsed ? 32 : 28'), 'creator avatars stay visible when collapsed')
assert(!sideSrc.includes('if (!open) return null'), 'sidebar icon rail stays mounted when collapsed')
assert(sideSrc.includes('flex flex-col shrink-0'), 'sidebar stays visible on all screen sizes')
assert(navSrc.includes('h-9 border') && !navSrc.includes('rounded-l-full'), 'header search bar is square and thinner')
const indexCss = readFileSync(new URL('../src/index.css', import.meta.url), 'utf8')
assert(indexCss.includes('--radius-button: 0'), 'buttons use square corners globally')
assert(appSrc.includes('migrateHashToPath'), 'old hash urls redirect to paths')
assert(!appSrc.includes('hashchange'), 'routing is not hash-based')
assert(!appSrc.includes("user?.creatorStatus !== 'approved'"), 'going live is not locked behind apply')
assert(!navSrc.includes('aria-label="Create"'), 'header has no Create button')
const notifMenu = readFileSync(new URL('../src/components/NotificationsMenu.jsx', import.meta.url), 'utf8')
assert(notifMenu.includes('slice(0, 5)'), 'header bell shows about five notifications')
assert(notifMenu.includes('Show more'), 'bell dropdown leads to the notifications page')
const followBtn = readFileSync(new URL('../src/components/FollowButton.jsx', import.meta.url), 'utf8')
assert(followBtn.includes("'Follow'") || followBtn.includes('"Follow"'), 'follow button exists')
assert(followBtn.includes('Following'), 'following state label exists')
assert(!followBtn.includes("'Subscribe'") && !followBtn.includes('"Subscribe"') && !followBtn.includes("'Subscribed'"), 'follow button does not say Subscribe')
assert(followBtn.includes('onOpenAuth'), 'follow opens sign-in when logged out')
const creatorPageSrc = readFileSync(new URL('../src/components/ProfilePage.jsx', import.meta.url), 'utf8')
assert(creatorPageSrc.includes('FollowButton'), 'creator page has follow')
assert(creatorPageSrc.includes('deleteCatalogItem'), 'creators can delete from their profile')
assert(!creatorPageSrc.includes('SubscribeButton'), 'creator page no longer imports SubscribeButton')
const shortsFeedSrc2 = readFileSync(new URL('../src/components/ShortsFeed.jsx', import.meta.url), 'utf8')
assert(shortsFeedSrc2.includes("'Follow'") || shortsFeedSrc2.includes('"Follow"'), 'clip player follow label')
assert(!shortsFeedSrc2.includes("'Subscribe'") && !shortsFeedSrc2.includes('"Subscribe"'), 'clip player does not say Subscribe')
const checkoutPageSrc = readFileSync(new URL('../src/components/CheckoutPage.jsx', import.meta.url), 'utf8')
assert(checkoutPageSrc.includes('Premium'), 'premium checkout keeps premium wording')
assert(!checkoutPageSrc.includes('Subscribe $') && !checkoutPageSrc.includes('Sign in to subscribe'), 'premium checkout does not say Subscribe')
const checkoutModalSrc2 = readFileSync(new URL('../src/components/CheckoutModal.jsx', import.meta.url), 'utf8')
assert(!checkoutModalSrc2.includes('Sign in to subscribe') && !checkoutModalSrc2.includes('Subscribe $'), 'premium modal does not say Subscribe')
assert(creatorPageSrc.includes("filter={tab === 'clips' ? 'clip'"), 'channel tabs only render that media type')
assert(creatorPageSrc.includes('stopPropagation'), 'pin control does not steal the video click')
const contentSvcSrc = readFileSync(new URL('../src/lib/contentService.js', import.meta.url), 'utf8')
assert(contentSvcSrc.includes('getCreatorPublicContent') && contentSvcSrc.includes('isFeedable'), 'public channel grids only list playable posts')
assert(contentSvcSrc.includes("lsGet('user_clips'") && contentSvcSrc.includes('export function getById'), 'getById can resolve legacy channel uploads')
const dashSrcPosts = readFileSync(new URL('../src/components/studio/CreatorStudio.jsx', import.meta.url), 'utf8')
assert(dashSrcPosts.includes('openPost') && dashSrcPosts.includes('onPlayItem'), 'dashboard posts open watch/clips')
assert(dashSrcPosts.includes('deleteCatalogItem'), 'creator studio can delete posts')
assert(dashSrcPosts.includes('Trash2'), 'creator studio shows delete control')
assert(dashSrcPosts.includes('InteractionBubbleMap'), 'studio analytics shows bubble map')
assert(dashSrcPosts.includes("section === 'analytics'"), 'bubble map lives under analytics')
const picsDeep = readFileSync(new URL('../src/components/PicsPage.jsx', import.meta.url), 'utf8')
assert(picsDeep.includes('onEnterPic') || picsDeep.includes('ENTER_ZOOM'), 'pics mosaic zooms then enters a photo')
assert(picsDeep.includes('key="pic-reel"'), 'pic reel stays mounted while scrolling')
assert(picsDeep.includes('tileAtViewportCenter') || picsDeep.includes('Zoom the mosaic'), 'pics zoom targets center photo')
const newsPage = readFileSync(new URL('../src/components/NewsPage.jsx', import.meta.url), 'utf8')
assert(!newsPage.includes('The Calabi Paper'), 'news has no paper masthead title')
assert(newsPage.includes('columns-') && newsPage.includes('text-justify'), 'news is a broadsheet of paragraphs')
assert(newsPage.includes('ComposePaper') && newsPage.includes('Publish to News'), 'news compose exists for studio')
assert(readFileSync(new URL('../src/components/studio/CreatorLab.jsx', import.meta.url), 'utf8').includes("mode === 'news'"), 'Calabi Studio has News publish tab')
assert(readFileSync(new URL('../src/components/CollapsibleSidebar.jsx', import.meta.url), 'utf8').includes('liveNow.length > 0'), 'empty lobby section is hidden between Following and Top creators')
const uploadSrc = readFileSync(new URL('../src/components/UploadModal.jsx', import.meta.url), 'utf8')
assert(uploadSrc.includes('priceUsd'), 'creators can price a post')
assert(watchSrc2.includes('clips_pending_purchase'), 'paid posts wait for Stripe return')
assert(watchSrc2.includes('Paid post'), 'watch shows paid overlay')
assert(watchSrc2.includes('NextStrip'), 'watch uses a horizontal next strip, not a YouTube right rail')
assert(!watchSrc2.includes('RelatedRow'), 'watch does not clone the YouTube related column')
const verifyLib = readFileSync(new URL('../src/lib/verification.js', import.meta.url), 'utf8')
assert(verifyLib.includes('frontFile') && verifyLib.includes('backFile'), 'checkmark needs front and back of ID')
assert(verifyLib.includes("status === 'approved'") || verifyLib.includes("nextStatus = status === 'approved'"), 'admin can accept an ID')
assert(verifyLib.includes("'denied'"), 'admin can deny an ID')
assert(verifyLib.includes('isOfficialCreator'), 'official channels keep checkmarks without ID')
assert(verifyLib.includes('isVerifiedChannel'), 'badges use official or accepted ID')
const verifyPage = readFileSync(new URL('../src/components/VerifyPage.jsx', import.meta.url), 'utf8')
assert(verifyPage.includes('Front of ID') && verifyPage.includes('Back of ID'), 'verify page asks for both sides')
assert(verifyPage.includes('Upload a photo of the front and the back of a government ID'), 'verify page uses clear ID copy')
assert(verifyPage.includes('7 business days'), 'verify page promises 7 business days')
assert(!verifyPage.includes('onBack='), 'verify page has no back button')
assert(verifyPage.includes('Site bubble') === false, 'verify is not stats')
const siteBubble = readFileSync(new URL('../src/components/studio/SiteBubbleMap.jsx', import.meta.url), 'utf8')
assert(siteBubble.includes('calabi'), 'site bubble hubs on calabi')
assert(siteBubble.includes('Lives') && siteBubble.includes('Dislikes'), 'site bubble shows lives and dislikes')
assert(siteBubble.includes('Likes'), 'site bubble keeps likes facet')
assert(siteBubble.includes('creators'), 'site bubble has creators facet')
assert(siteBubble.includes("label: 'Views'"), 'site bubble has views facet')
assert(siteBubble.includes('recordView'), 'opening site bubble items logs views like analytics')
assert(siteBubble.includes('data-bubble-node'), 'site bubble nodes are clickable hit targets')
assert(!siteBubble.includes('setPointerCapture'), 'site bubble does not steal clicks with pointer capture')
assert(!siteBubble.includes('calabi at the center'), 'site bubble drops old center copy')
assert(siteBubble.includes('setExpandedId') || siteBubble.includes('expand'), 'site bubble sections expand on click')
assert(siteBubble.includes('buildChildPeople') || siteBubble.includes('buckets'), 'site bubble expands into item bubbles')
assert(siteBubble.includes('All sections'), 'expanded site bubble can return to overview')
assert(siteBubble.includes('fitZ'), 'site bubble camera defaults to fit zoom')
assert(!siteBubble.includes('Tip: click any section bubble'), 'site bubble has no tip under the map')
const statsPage = readFileSync(new URL('../src/components/StatsPage.jsx', import.meta.url), 'utf8')
assert(statsPage.includes('SiteBubbleMap'), 'stats page shows site bubble')
assert(statsPage.includes('buckets={bubbleBuckets}') || statsPage.includes('bubbleBuckets'), 'stats passes catalog buckets into site bubble')
assert(statsPage.includes('views=') || statsPage.includes('views={'), 'stats passes views count')
assert(!statsPage.includes('Catalog safety backup'), 'catalog backup UI stays out of the public stats page')
assert(!statsPage.includes('Press Likes'), 'stats does not advertise press-to-expand on KPI cards')
assert(!statsPage.includes('openFacet') && !statsPage.includes('focusFacet'), 'stats KPI cards are not press-to-expand controls')
assert(!statsPage.includes('Counts from this catalog'), 'stats has no catalog copy line')
assert(statsPage.includes('Premium subscribers') && statsPage.includes("'Lives'"), 'stats KPIs include lives and premium')
assert(!statsPage.includes('Approved Creators') && !statsPage.includes('Catalog Duration'), 'stats KPI list is trimmed')
assert(!statsPage.includes('interactions='), 'stats uses views not interactions')
assert(siteBubble.includes('label: \'Views\'') || siteBubble.includes('Views'), 'site bubble facet is Views not Interactions')
assert(!siteBubble.includes('label: \'Interactions\''), 'interactions facet renamed to views')
const payoutVault = readFileSync(new URL('../src/lib/payoutVault.js', import.meta.url), 'utf8')
assert(payoutVault.includes('storePayoutSecret'), 'bank/crypto secrets go in payout vault')
const earnPanel = readFileSync(new URL('../src/components/studio/CreatorEarningsPanel.jsx', import.meta.url), 'utf8')
assert(earnPanel.includes('Routing number') || earnPanel.includes('routingNumber'), 'earnings asks for bank routing')
assert(earnPanel.includes('SOL') && earnPanel.includes('BTC'), 'earnings supports SOL and BTC')
assert(earnPanel.includes('Request withdrawal') && earnPanel.includes('Add payment method'), 'withdraw methods and request are combined')
const vodLink = readFileSync(new URL('../src/lib/vodAccountLink.js', import.meta.url), 'utf8')
assert(vodLink.includes('startVodAccountLink') && vodLink.includes('confirmVodAccountLink'), 'VOD second account email code link')
const bubbleMap = readFileSync(new URL('../src/components/studio/InteractionBubbleMap.jsx', import.meta.url), 'utf8')
assert(bubbleMap.includes('keepHubInView'), 'bubble zoom keeps hub on screen')
assert(bubbleMap.includes('min-h-0'), 'bubble map viewport fills its container')
assert(!bubbleMap.includes('min-h-[480px]'), 'bubble map does not force a taller box than parent')
assert(bubbleMap.includes('prepareBubblePopulation') && bubbleMap.includes('layoutBubbleNetwork'), 'bubble map uses scale engine')
assert(bubbleMap.includes('clampPanToBox'), 'bubble pan stays inside the box')
assert(bubbleMap.includes('setPointerCapture'), 'bubble map captures pointer while dragging')
assert(!bubbleMap.includes('function ColorLegend') && !bubbleMap.includes('>Legend<'), 'post bubble has no second ColorLegend')
assert(bubbleMap.includes('setZoom(fitZ)') || bubbleMap.includes('return fitZ'), 'analytics bubble resets camera to fit zoom so content stays in the box')
assert(bubbleMap.includes('studio-grid'), 'analytics bubble keeps grid backdrop')
assert(!bubbleMap.includes('zoom.toFixed'), 'analytics bubble has no 1x/2x zoom readout')
assert(bubbleMap.includes('Backdrop stays put') || bubbleMap.includes('pointer-events-none'), 'grid backdrop is not inside the zoom transform')
assert(bubbleMap.includes('Post hub') || bubbleMap.includes('Post bubble'), 'analytics keeps the post hub bubble')
assert(!bubbleMap.includes('Unique viewers'), 'studio bubble copy says views not viewers')
assert(!bubbleMap.includes('Sync cloud'), 'analytics bubble has no Sync cloud button')
const dashAnalyticsBox = readFileSync(new URL('../src/components/studio/CreatorStudio.jsx', import.meta.url), 'utf8')
assert(dashAnalyticsBox.includes('min(78vh') || dashAnalyticsBox.includes('min-h-[520px]'), 'analytics post bubble container is larger')
const walletSettings = readFileSync(new URL('../src/components/settings/WalletSettings.jsx', import.meta.url), 'utf8')
assert(walletSettings.includes("id: 'orders'") && walletSettings.includes("id: 'coins'"), 'wallet has Coins and Orders tabs')
assert(walletSettings.includes('listCoinLedger') || walletSettings.includes('CoinOrders'), 'Orders tab lists coin ledger')
assert(walletSettings.includes('title="Coins"'), 'wallet page is titled Coins')
assert(settingsLayoutSrc.includes("label: 'Coins'"), 'settings sidebar says Coins')
assert(!settingsLayoutSrc.includes('Wallet & Coins'), 'settings sidebar no longer says Wallet & Coins')
const bubbleEngine = readFileSync(new URL('../src/lib/bubbleEngine.js', import.meta.url), 'utf8')
assert(bubbleEngine.includes('freeSlack'), 'pan clamp allows free drag slack when content fits')
assert(bubbleEngine.includes('BUBBLE_VISUAL_CAP') && bubbleEngine.includes('prepareBubblePopulation'), 'bubble engine caps millions')
const siteBubbleZoom = readFileSync(new URL('../src/components/studio/SiteBubbleMap.jsx', import.meta.url), 'utf8')
assert(siteBubbleZoom.includes('Backdrop stays put') || siteBubbleZoom.includes('only bubbles zoom'), 'site bubble backdrop does not zoom')
assert(siteBubble.includes('layoutBubbleNetwork') && siteBubble.includes('clampPanToBox'), 'site bubble fits box via engine')
const dashSrcCopy = dashAnalyticsBox
assert(!dashSrcCopy.includes('meta.subtitle'), 'creator studio tabs have no subtitle microcopy under titles')
assert(dashSrcCopy.includes("label: 'Views'"), 'creator studio channel stats say Views')
assert(!dashSrcCopy.includes('Unique viewers'), 'creator studio does not say Unique viewers')
assert(dashSrcCopy.includes("id: 'content'"), 'creator studio has Content tab')
assert(!dashSrcCopy.includes("id: 'controls'") || dashSrcCopy.includes('labTool'), 'controls live inside Calabi Studio')
assert(dashSrcCopy.includes('ContentLibrary') || dashSrcCopy.includes('section === \'content\''), 'content library section exists')
assert(!dashSrcCopy.includes('@{user?.handle'), 'creator studio header has no @username under title')
const realtimeSrc = readFileSync(new URL('../src/components/studio/StudioRealtimeAnalytics.jsx', import.meta.url), 'utf8')
assert(!realtimeSrc.includes('Unique viewers'), 'realtime analytics says Views not Unique viewers')
assert(!realtimeSrc.includes('Stats for the selected post'), 'realtime analytics drops subtitle under Analytics title')
assert(!realtimeSrc.includes("'{refreshing ? 'Syncing") && !realtimeSrc.includes('>Sync<') && !realtimeSrc.includes("'{refreshing ? \"Syncing"), 'realtime analytics has no Sync button')
assert(!realtimeSrc.includes("Syncing…' : 'Sync'"), 'realtime analytics removed Sync control')
const catalogBackup = readFileSync(new URL('../src/lib/catalogBackup.js', import.meta.url), 'utf8')
assert(catalogBackup.includes('snapshotCatalogBackup') && catalogBackup.includes('restoreCatalogBackup'), 'catalog backup can snapshot and restore')
const contentSvcSafety = readFileSync(new URL('../src/lib/contentService.js', import.meta.url), 'utf8')
assert(contentSvcSafety.includes('intentional'), 'deleteCatalogItem requires intentional flag')
assert(contentSvcSafety.includes('snapshotCatalogBackup'), 'intentional deletes snapshot backup first')
const contentSyncSafety = readFileSync(new URL('../src/lib/contentSync.js', import.meta.url), 'utf8')
assert(contentSyncSafety.includes('snapshotCatalogBackup'), 'cloud sync snapshots catalog backup after pull')
assert(readFileSync(new URL('../src/components/studio/CreatorStudio.jsx', import.meta.url), 'utf8').includes('intentional: true'), 'studio delete is intentional')
assert(readFileSync(new URL('../src/components/ProfilePage.jsx', import.meta.url), 'utf8').includes('intentional: true'), 'profile delete is intentional')
assert(readFileSync(new URL('../src/lib/creatorInteractions.js', import.meta.url), 'utf8').includes('stats:'), 'stats surface is tracked in analytics')
assert(readFileSync(new URL('../src/lib/creatorInteractions.js', import.meta.url), 'utf8').includes('aggregateInteractionsByContent'), 'site interactions facet aggregates real events')
const apiPage = readFileSync(new URL('../src/components/BubbleApiPage.jsx', import.meta.url), 'utf8')
assert(apiPage.includes("from '../context/AuthContext'") || apiPage.includes('from "../context/AuthContext"'), 'Bubble API page imports useAuth from AuthContext')
assert(!apiPage.includes("from '../lib/auth'"), 'Bubble API page does not import missing lib/auth')
assert(apiPage.includes('Embed Widget') && apiPage.includes('REST Graph Snapshot'), 'API page documents embed + REST')
assert(apiPage.includes('Live Event Stream') && apiPage.includes('Webhook'), 'API page documents stream + webhooks')
assert(apiPage.includes('White-label') && apiPage.includes('Batch Analytics') && apiPage.includes('Graph Query'), 'API page documents SDK export query')
assert(existsSync(new URL('../app/api/page.jsx', import.meta.url)), 'api route exists')
assert(readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8').includes("'api'"), 'App knows api view')
const socialsPanel = readFileSync(new URL('../src/components/studio/StudioSocialsPanel.jsx', import.meta.url), 'utf8')
assert(socialsPanel.includes('ProviderGlyph') && socialsPanel.includes('showOnProfile'), 'socials use icons and profile toggles')
const profilePage = readFileSync(new URL('../src/components/ProfilePage.jsx', import.meta.url), 'utf8')
assert(profilePage.includes("label: 'Clips'"), 'profile clips tab is labeled Clips')
const contentVis = readFileSync(new URL('../src/lib/contentService.js', import.meta.url), 'utf8')
assert(contentVis.includes('setContentVisibility'), 'creators can set public/private')
assert(contentVis.includes("visibility === 'private'"), 'private content stays off public feeds')
assert(verifyPage.includes('with or without creator status') === false, 'old verify copy removed')
const contentSyncSrc = readFileSync(new URL('../src/lib/contentSync.js', import.meta.url), 'utf8')
assert(contentSyncSrc.includes('visibility:'), 'content sync pushes visibility to cloud')
const mig21 = readFileSync(new URL('../supabase/migrations/0021_visibility_payout_secrets.sql', import.meta.url), 'utf8')
assert(mig21.includes('payout_secrets') && mig21.includes('visibility'), 'migration 0021 adds visibility + payout secrets')
const mailSrc = readFileSync(new URL('../src/lib/mail.js', import.meta.url), 'utf8')
assert(mailSrc.includes('sendVerificationCodeEmail'), 'mail helper exists for verification codes')
const liveLobbySrc = readFileSync(new URL('../src/lib/liveLobby.js', import.meta.url), 'utf8')
assert(liveLobbySrc.includes('startLiveLobby') && liveLobbySrc.includes('stopLiveLobby'), 'live lobby start/stop helpers exist')
const socialTruth = readFileSync(new URL('../src/lib/socialConnects.js', import.meta.url), 'utf8')
assert(socialTruth.includes('socialOAuthConfigured'), 'social publish gated on OAuth env')
assert(socialTruth.includes('Publish APIs are not connected') || socialTruth.includes('not connected yet'), 'socials refuse fake queue without OAuth')
const labLive = readFileSync(new URL('../src/components/studio/CreatorLab.jsx', import.meta.url), 'utf8')
assert(labLive.includes('startLiveLobby') && labLive.includes('End lobby'), 'Calabi Studio can start/end lobby')
const adminSafetySrc = readFileSync(new URL('../src/components/admin/AdminSafety.jsx', import.meta.url), 'utf8')
assert(adminSafetySrc.includes('ID checks'), 'admin has ID checks tab')
assert(adminSafetySrc.includes('Accept') && adminSafetySrc.includes('Deny'), 'admin can accept or deny ID')
assert(adminSafetySrc.includes('setIdVerificationStatus'), 'admin writes ID review')
assert(appSrc.includes("initialSection=\"verify\"") || appSrc.includes("initialSection='verify'"), 'verify opens inside creator studio')
assert(appSrc.includes("'verify'"), 'verify is a known view')
const channelSet = readFileSync(new URL('../src/components/settings/ChannelSettings.jsx', import.meta.url), 'utf8')
assert(channelSet.includes('Get a checkmark') || channelSet.includes('View checkmark'), 'settings links to ID checkmark')
assert(!channelSet.includes('There is no verification queue yet'), 'settings no longer says checkmark is missing')
const stampSrc = readFileSync(new URL('../src/components/PostedStamp.jsx', import.meta.url), 'utf8')
assert(stampSrc.includes('formatPostedAt'), 'posted stamp ages over time')

const kidsSrc = readFileSync(new URL('../src/data/publicMediaSeed.js', import.meta.url), 'utf8')
assert(kidsSrc.includes("handle: 'nasa'"), 'nasa creator channel')
assert(kidsSrc.includes('yt3.googleusercontent.com'), 'library channels use YouTube avatars')
assert(kidsSrc.includes('bpfrBmM6vZk'), 'nasa connect uses eClips youtube art')
assert(kidsSrc.includes('official-pd-v6'), 'catalog generation refreshes timestamps')
assert(!kidsSrc.includes('1969-07-24'), 'library posts are dated today not 1969')
assert(kidsSrc.includes("handle: 'noaa'"), 'noaa creator channel')
assert(kidsSrc.includes("handle: 'esa'"), 'esa creator channel')
assert(kidsSrc.includes("handle: 'nasaconnect'"), 'nasa connect kids channel')
assert(kidsSrc.includes("handle: 'classroom'"), 'classroom films channel')
assert(kidsSrc.includes("handle: 'nara'"), 'national archives channel')
assert(kidsSrc.includes('archive.org/download'), 'archive.org documentaries')
assert(kidsSrc.includes("'kids'"), 'kids tagged films')
assert(kidsSrc.includes("'maths'"), 'maths films')
assert(kidsSrc.includes("'english'"), 'english films')
assert(kidsSrc.includes("'history'"), 'history films')
assert(kidsSrc.includes("'documentary'"), 'documentaries')
assert(kidsSrc.includes('durationSec: 1710'), 'long nasa connect programme')
assert(kidsSrc.includes('durationSec: 3140'), 'long history documentary')
assert(kidsSrc.includes("creatorStatus: 'approved'"), 'official channels are creators')
assert(kidsSrc.includes('https://images-assets.nasa.gov'), 'nasa public media')
assert(kidsSrc.includes('https://upload.wikimedia.org'), 'commons public media')
assert(!/oraknebara|or%c3%a4knebara|substantiv/i.test(kidsSrc), 'no foreign-language nouns video')
assert(!/picsum|placekitten|sample-videos|gtv-videos/i.test(kidsSrc), 'official media is not placeholder hosts')
assert(kidsSrc.includes("type: 'video'"), 'official library has videos')
assert(kidsSrc.includes("type: 'short'"), 'official library has clips')
assert(kidsSrc.includes("type: 'pic'"), 'official library has photos')
assert(kidsSrc.includes("lsSet(GEN_KEY, CATALOG_GENERATION)"), 'catalog generation is stored so dates refresh')
assert(kidsSrc.includes('export function findOfficialLogin'), 'library channels have site logins')
assert((kidsSrc.match(/email: '[\w.]+@calabi\.local'/g) || []).length >= 7, 'each official channel has a site email')
assert((kidsSrc.match(/passwordHash: 'sha256\$/g) || []).length >= 7, 'channel passwords are hashed not stored in the open')
const authCtx = readFileSync(new URL('../src/context/AuthContextBody.jsx', import.meta.url), 'utf8')
assert(authCtx.includes('findOfficialLogin'), 'sign-in intercepts library channel emails')
assert(authCtx.includes('findOwnerLogin'), 'owner login runs in auth')
const officialAt = authCtx.indexOf('findOfficialLogin(email)')
const namedAt = authCtx.indexOf('findNamedAccountLogin(email)')
const genericCloudAt = authCtx.indexOf('isSupabaseConfigured() && email && password')
assert(officialAt >= 0 && officialAt < genericCloudAt, 'library logins run before cloud auth')
assert(authCtx.includes('findNamedAccountLogin'), 'named people accounts can sign in')
assert(namedAt >= 0 && namedAt < genericCloudAt, 'named logins run before cloud auth')
const namedCsv = readFileSync(new URL('../src/data/namedAccounts.csv', import.meta.url), 'utf8').trim().split(/\n/)
assert(namedCsv.length === 468, '467 named accounts plus header')
assert(namedCsv[1].startsWith('1,Lucy,Bennett,'), 'first named account is Lucy Bennett')
assert(namedCsv[467].startsWith('467,Sophia,Wood,'), 'last named account is Sophia Wood')
const namedSrc = readFileSync(new URL('../src/data/namedAccountsSeed.js', import.meta.url), 'utf8')
assert(namedSrc.includes("name${n}@calabi.com"), 'named emails are nameN@calabi.com')
assert(namedSrc.includes("Hoka${String(id).padStart(4, '0')}"), 'named passwords follow Hoka0001 pattern')
assert(namedSrc.includes("BLACK_PROFILE_URL = '/media/black.png'"), 'named accounts use the black profile image')
const blackPng = readFileSync(new URL('../public/media/black.png', import.meta.url))
assert(blackPng[0] === 0x89 && blackPng[1] === 0x50 && blackPng[2] === 0x4e && blackPng[3] === 0x47, 'black profile file is a png')
const profileSrc = readFileSync(new URL('../src/lib/profileMedia.js', import.meta.url), 'utf8')
assert(profileSrc.includes('isSiteProfileAsset'), 'black site avatars are allowed to persist')
const healSrc = readFileSync(new URL('../src/lib/selfHeal.js', import.meta.url), 'utf8')
assert(healSrc.includes('seedOfficialCatalog'), 'official catalog seeds on boot')
assert(healSrc.includes('seedNamedAccounts'), 'named people accounts seed on boot')
assert(healSrc.includes('users_index'), 'boot repair reindexes creators from posts')
assert(!healSrc.includes('seedKidsEducation'), 'kids filler seed is gone')
const healthSrc2 = readFileSync(new URL('../src/lib/catalogHealth.js', import.meta.url), 'utf8')
assert(healthSrc2.includes('isRetiredCatalogItem'), 'old kids seed rows cannot return')

const namedAct = readFileSync(new URL('../src/lib/namedAccountActivity.js', import.meta.url), 'utf8')
assert(namedAct.includes('Named-account bots are off'), 'browser named-account bots are removed')
assert(!namedAct.includes('setInterval'), 'browser named bots do not tick')
assert(!namedAct.includes('ensureUpvote'), 'browser named bots do not like')
const appSrc2 = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
assert(!appSrc2.includes('startNamedAccountActivity'), 'the app does not start named bots')
const engSrc = readFileSync(new URL('../src/lib/engagement.js', import.meta.url), 'utf8')
assert(engSrc.includes('export function ensureUpvote'), 'likes can be applied without unliking')
const namedSql = readFileSync(new URL('../supabase/migrations/0009_named_activity.sql', import.meta.url), 'utf8')
assert(namedSql.includes('create table if not exists public.named_people'), '0009 stores the 467 people')
assert((namedSql.match(/named-\d{4}/g) || []).length >= 467, '0009 seeds 467 named ids')
assert(namedSql.includes('run_named_activity'), '0009 still has the old activity function')
assert(namedSql.includes("values (pid, cid, 'up')"), 'old job only inserted up votes')
assert(!/insert into public\.comments/i.test(namedSql), 'job never comments')
assert(!/live_chat/i.test(namedSql), 'job never writes live chat')
const stopSql = readFileSync(new URL('../supabase/migrations/0010_stop_named_activity.sql', import.meta.url), 'utf8')
assert(stopSql.includes("cron.unschedule('clips-named-activity')"), '0010 unschedules the named bot job')
assert(stopSql.includes('revoke execute on function public.run_named_activity'), '0010 revokes the bot function')
const scriptsSrc = readFileSync(new URL('../src/data/supabaseScripts.js', import.meta.url), 'utf8')
assert(scriptsSrc.includes('0009_named_activity.sql'), 'admin can copy 0009')
assert(scriptsSrc.includes('0010_stop_named_activity.sql'), 'admin can copy 0010')
assert(scriptsSrc.includes('0012_videos_publish_columns.sql'), 'admin can copy 0012 upload fix')
const publishColsSql = readFileSync(new URL('../supabase/migrations/0012_videos_publish_columns.sql', import.meta.url), 'utf8')
assert(publishColsSql.includes('published_at'), '0012 adds published_at for catalog upsert')
const orgSrc = readFileSync(new URL('../src/lib/orgConfig.js', import.meta.url), 'utf8')
assert(orgSrc.includes('supabase.com/dashboard/project/'), 'sql editor url is the supabase dashboard')
const adminSetupSrc2 = readFileSync(new URL('../src/components/AdminSetup.jsx', import.meta.url), 'utf8')
assert(adminSetupSrc2.includes('0010'), 'admin setup tells you to stop the named bot job')
const graphSrc2 = readFileSync(new URL('../src/lib/graphSync.js', import.meta.url), 'utf8')
assert(graphSrc2.includes('syncPublicEngagementFromCloud'), 'clients pull like tallies without signing in')
assert(graphSrc2.includes('vote_tallies'), 'like counts come from vote_tallies')

const before31 = new Date(2026, 7, 24, 14, 10, 0).getTime()
const at31 = new Date(2026, 7, 24, 14, 31, 0).getTime()
const startBefore = new Date(featuredWindowStart(before31))
assert(startBefore.getHours() === 13 && startBefore.getMinutes() === 31, 'before :31 the lineup is from last hour :31')
const startAt = new Date(featuredWindowStart(at31))
assert(startAt.getHours() === 14 && startAt.getMinutes() === 31, 'at :31 the lineup refreshes')
assert(nextFeaturedRefreshAt(at31) === featuredWindowStart(at31) + 3600000, 'next refresh is one hour later')
const range = lastHourRange(at31)
assert(range.end - range.start === 3600000, 'ranking window is the previous hour')
assert(HOURLY_PATTERN.filter((t) => t === 'video').length === HOURLY_VIDEO_COUNT, 'stage mix has 5 videos')
assert(HOURLY_PATTERN.filter((t) => t === 'short').length === HOURLY_CLIP_COUNT, 'stage mix has 10 clips')
assert(HOURLY_PATTERN.filter((t) => t === 'pic').length === HOURLY_PIC_COUNT, 'stage mix has 3 pics')
const mixed = interleaveHourlyHits(
  Array.from({ length: 5 }, (_, i) => ({ id: `v${i}`, type: 'video' })),
  Array.from({ length: 10 }, (_, i) => ({ id: `c${i}`, type: 'short' })),
  Array.from({ length: 3 }, (_, i) => ({ id: `p${i}`, type: 'pic' })),
)
assert(mixed.length === 18, 'hourly stage holds 18 posts when the catalog is full')
assert(mixed.filter((i) => i.type === 'video').length === 5, 'interleave keeps 5 videos')
assert(mixed.filter((i) => i.type === 'short').length === 10, 'interleave keeps 10 clips')
assert(mixed.filter((i) => i.type === 'pic').length === 3, 'interleave keeps 3 pics')
const homeSrc2 = readFileSync(new URL('../src/components/HomeFeed.jsx', import.meta.url), 'utf8')
assert(homeSrc2.includes('HourlyHitsCarousel'), 'home puts the hourly stage under the search bar')
const carouselSrc = readFileSync(new URL('../src/components/HourlyHitsCarousel.jsx', import.meta.url), 'utf8')
assert(carouselSrc.includes('useContentSyncTick'), 'hourly stage refreshes after catalog sync')
assert(carouselSrc.includes('onOpenProfile'), 'hourly stage separates profile from play')
assert(carouselSrc.includes('openProfile'), 'hourly stage avatar opens profile not the video')
assert(carouselSrc.includes('@{String(current.handle') || carouselSrc.includes('@${String(current.handle'), 'hourly stage overlay is @creator only')
assert(!carouselSrc.includes("current.title || 'Untitled'"), 'hourly stage does not overlay the post title')
assert(carouselSrc.includes('ChevronLeft') && carouselSrc.includes('ChevronRight'), 'hourly stage has twitch-style arrows')
assert(carouselSrc.includes('4000'), 'hourly stage auto-advances every 4 seconds')
assert(!carouselSrc.includes('rounded-full bg-black/70'), 'hourly stage arrows have no black circles')
assert(!carouselSrc.includes('New lineup at'), 'hourly stage has no lineup clock copy')
assert(!carouselSrc.includes('Last hour'), 'hourly stage has no last-hour label')
assert(!carouselSrc.includes('typeMeta'), 'hourly stage does not stamp clip/video/pic')
const hitsSrc = readFileSync(new URL('../src/lib/hourlyHits.js', import.meta.url), 'utf8')
assert(hitsSrc.includes('engagement_views') && hitsSrc.includes('clips_content_views'), 'stage ranks on all stored views')
assert(!hitsSrc.includes('hourViewCount'), 'stage is not ranked on last-hour-only views')
const engagementHits = readFileSync(new URL('../src/lib/engagement.js', import.meta.url), 'utf8')
assert(engagementHits.includes('recordHourView'), 'views in the last hour are counted for the stage')
const miniSrc = readFileSync(new URL('../src/components/MiniPlayer.jsx', import.meta.url), 'utf8')
assert(miniSrc.includes('top-[3.75rem]') && miniSrc.includes('right-3'), 'docked watch player sits top right')
assert(!miniSrc.includes('bottom-3 right-3'), 'docked watch player is not bottom right')
const tipsSrc = readFileSync(new URL('../src/lib/tips.js', import.meta.url), 'utf8')
assert(tipsSrc.includes('membershipReturnPaid'), 'tips wait for a Stripe return')
assert(tipsSrc.includes('live_tip') && tipsSrc.includes('post_tip'), 'live and post tips exist')
assert(!tipsSrc.includes('granted: true'), 'tips never grant access without the checkout gate')
assert(tipsSrc.includes("return { ok: false, kind: '' }"), 'a stripe return without a pending checkout does not invent premium')
assert(appSrc.includes('claimStripeReturn'), 'app applies Stripe returns in one place')
assert(appSrc.includes('addPremiumSub'), 'premium Stripe return grants membership')
assert(appSrc.includes("kind === 'checkout'"), 'checkout route reads creator from URL params')
assert(!healSrc.includes('r.priceUsd = 0'), 'boot heal does not wipe paid post prices')
assert(publishSrc.includes('finalPrice'), 'video publish persists upload price')
const chatLib = readFileSync(new URL('../src/lib/liveChat.js', import.meta.url), 'utf8')
assert(chatLib.includes('trySendLiveChat'), 'live chat enforces slow mode and bans')
assert(chatLib.includes('!rules'), 'chat bots reply to !rules')
assert(!chatLib.includes('parseAdSlash'), 'live chat no longer wires !ad commands')
const rolesSrc = readFileSync(new URL('../src/components/settings/RolesSettings.jsx', import.meta.url), 'utf8')
assert(rolesSrc.includes('addRole'), 'streamers can assign mods')
assert(rolesSrc.includes('addBotCommand'), 'streamers can add bot commands')
assert(!rolesSrc.includes('not assignable yet'), 'roles are no longer a placeholder')
assert(settingsHub.includes('CommentSettings'), 'comments settings page is mounted')
const commentSet = readFileSync(new URL('../src/components/settings/CommentSettings.jsx', import.meta.url), 'utf8')
assert(commentSet.includes('showDonationsOnComments'), 'comment settings can hide donation amounts')
const liveViewSrc = readFileSync(new URL('../src/components/LiveView.jsx', import.meta.url), 'utf8')
assert(liveViewSrc.includes('getDisplayMedia'), 'PC screen share uses the browser capture API')
assert(liveSrc.includes('getDisplayMedia') || liveViewSrc.includes('Share this screen'), 'live has share this screen')
const panelSrc = readFileSync(new URL('../src/components/LiveChatPanel.jsx', import.meta.url), 'utf8')
assert(panelSrc.includes('chatSettingsOpen'), 'live chat settings state is defined')
assert(tipsSrc.includes('normalizeTipAmount'), 'tips accept custom amounts')
assert(tipsSrc.includes('TIP_AMOUNT_MIN'), 'tips have a minimum donation')
assert(panelSrc.includes('Send a message'), 'global/live chat has a message input')
assert(!panelSrc.includes('{!channel ? null'), 'global chat composer is not gated on a focused stream')
assert(panelSrc.includes('startTipCheckout'), 'live chat has donate amounts')
assert(panelSrc.includes('aria-live'), 'live chat announces new messages')
assert(panelSrc.includes('subscribeLiveChat') || panelSrc.includes('liveChatSync'), 'live chat syncs from cloud')
assert(watchSrc2.includes('placeholder="Other"'), 'watch page has custom donate')
assert(panelSrc.includes("kind === 'donation'"), 'live donations render in chat')

assert(EXOCLICK_VAST_URL === '', 'no live ExoClick VAST URL to probe')

if (failed) {
  console.error(`${failed} failed`)
  process.exit(1)
}
console.log('all good')
console.log('all smoke checks passed')
