/** Live-project smoke checks — no mock catalog, no invented checkout grant. */
import { readFileSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { extractHashtags, mergeTags, parseClock, parseCaptionCues, isReleased, filterExploreItems, formatPostedAt, olderIso, postedAtOf } from '../src/lib/mediaMeta.js'
import { parseRoute, buildHash } from '../src/lib/routes.js'
import { sanitizeAuthError, normalizePhone } from '../src/lib/authBrand.js'
import { findOwnerLogin, isLocalOwnerLogin, isOwnerAccount, OWNER_LOGIN } from '../src/data/ownerLogin.js'
import { parseVastXml, parseVastClock, youtubeMidrollBreaks, EXOCLICK_VAST_URL, YT_MIDROLL_MIN_SEC } from '../src/lib/vastAds.js'
import { featuredWindowStart, nextFeaturedRefreshAt, lastHourRange, interleaveHourlyHits, HOURLY_PATTERN, HOURLY_VIDEO_COUNT, HOURLY_CLIP_COUNT, HOURLY_PIC_COUNT } from '../src/lib/hourWindow.js'

let failed = 0
function assert(cond, msg) {
  if (!cond) {
    failed += 1
    console.error('FAIL', msg)
  } else {
    console.log('ok', msg)
  }
}

assert(sanitizeAuthError('Invalid login credentials') === 'Wrong email or password.', 'branded login error')
assert(!/supabase/i.test(sanitizeAuthError('supabase provider is not enabled')), 'errors never say supabase')
assert(normalizePhone('5551234567') === '+15551234567', 'us phone to e164')

assert(extractHashtags('hello #Music and #gaming').join(',') === 'music,gaming', 'hashtags')
assert(mergeTags('music, extra', 'more #music #live').includes('live'), 'merge tags')
assert(parseClock('1:02') === 62, 'parse clock')
const now = Date.parse('2026-08-24T12:00:00.000Z')
assert(formatPostedAt(now, now) === 'just now', 'brand new post is just now')
assert(formatPostedAt(now - 3600_000, now) === 'today', 'same-day post says today')
assert(formatPostedAt(now - 36 * 3600_000, now) === '1d ago', 'yesterday keeps days')
assert(formatPostedAt('', now) === '', 'missing date is blank not just now')
assert(olderIso('1969-07-24T16:00:00.000Z', new Date(now).toISOString()) === '1969-07-24T16:00:00.000Z', 'cloud now does not erase real date')
assert(formatPostedAt(postedAtOf({ id: 'org-nasa-iss', origin: 'public-domain-org', createdAt: '1969-07-24T16:00:00.000Z' })) === 'today', 'library 1969 stamp displays as today')
assert(formatPostedAt(postedAtOf({ id: 'user-1', createdAt: '1969-12-31T00:00:00.000Z' })) === 'today', 'epoch junk dates display as today')
assert(parseCaptionCues('00:00.000 --> 00:02.000\nHi').length === 1, 'vtt cues')
assert(isReleased({ status: 'draft' }) === false, 'draft hidden')
assert(isReleased({ status: 'published' }) === true, 'published visible')
assert(isReleased({ status: 'scheduled', scheduledFor: new Date(Date.now() + 864e5).toISOString() }) === false, 'future schedule hidden')

const { kind, id, params } = parseRoute('#/watch/abc?t=12')
assert(kind === 'watch' && id === 'abc' && params.t === '12', 'watch timestamp route')
assert(buildHash('watch', 'abc', { t: 12 }) === '/watch/abc?t=12', 'path route with t')
assert(!buildHash('watch', 'abc').includes('#'), 'share paths do not use hash')
const pathParsed = parseRoute('/watch/abc?t=12')
assert(pathParsed.kind === 'watch' && pathParsed.id === 'abc' && pathParsed.params.t === '12', 'pathname watch route')
assert(buildHash('home') === '/', 'home is slash')
assert(parseVastClock('00:00:05.0') === 5, 'vast skipoffset clock')
assert(youtubeMidrollBreaks(YT_MIDROLL_MIN_SEC - 1).length === 0, 'no mid-roll under 8 minutes')
assert(youtubeMidrollBreaks(8 * 60).length === 1, '8 minute video gets one mid-roll')
assert(EXOCLICK_VAST_URL.includes('idz=6010924'), 'exoClick zone is wired')
{
  const sample = '<?xml version="1.0"?><VAST version="3.0"><Ad><InLine><Impression><![CDATA[https://s.magsrv.com/i]]></Impression><Creatives><Creative><Linear skipoffset="00:00:05.0"><Duration>00:00:17.500</Duration><MediaFiles><MediaFile delivery="progressive" type="video/mp4"><![CDATA[https://cdn.example.com/ad.mp4]]></MediaFile></MediaFiles><VideoClicks><ClickThrough><![CDATA[https://s.magsrv.com/click]]></ClickThrough></VideoClicks></Linear></Creative></Creatives></InLine></Ad></VAST>'
  const parsed = parseVastXml(sample)
  assert(parsed?.mediaUrl?.includes('ad.mp4') && parsed.skipAfterSec === 5, 'vast parser reads mp4 and skip')
}
assert(!parseVastXml('<VAST version="3.0"></VAST>'), 'empty vast is not a fake ad')
{
  const mixed = []
  for (let i = 0; i < 20; i += 1) {
    mixed.push({ kind: 'item', item: { id: `c${i}` } })
    if ((i + 1) % 4 === 0 && i < 19) mixed.push({ kind: 'ad', ad: { provider: 'exoclick' } })
  }
  function allowed(index) {
    const row = mixed[index]
    if (!row || row.kind === 'ad') return false
    if (mixed[index - 1]?.kind === 'ad' || mixed[index + 1]?.kind === 'ad') return false
    const n = mixed.slice(0, index + 1).filter((r) => r.kind === 'item').length
    return n > 0 && n % 15 === 0
  }
  const bannerIdx = mixed.findIndex((_, i) => allowed(i))
  assert(bannerIdx >= 0 && mixed[bannerIdx].kind === 'item', 'every 15th clip can show a banner')
  assert(mixed[bannerIdx - 1]?.kind !== 'ad' && mixed[bannerIdx + 1]?.kind !== 'ad', 'clip banner is not next to a full ad')
}
assert(existsSync(new URL('../public/_redirects', import.meta.url)), 'static host rewrites unknown paths to the app')

function isPromoLive(promo, now = Date.now()) {
  if (!promo || promo.published !== true) return false
  if (promo.startsAt) {
    const t = new Date(promo.startsAt).getTime()
    if (t && t > now) return false
  }
  if (promo.endsAt) {
    const t = new Date(promo.endsAt).getTime()
    if (t && t < now) return false
  }
  return true
}
assert(isPromoLive({ published: false }) === false, 'unpublished promo hidden')
assert(isPromoLive({ published: true }) === true, 'published promo live')
assert(isPromoLive({ published: true, startsAt: new Date(Date.now() + 864e5).toISOString() }) === false, 'future promo hidden')

function startPremiumCheckout({ already = false, configured = false, link = '' } = {}) {
  if (already) return { granted: false, status: 'already' }
  if (link) return { granted: false, status: 'redirect', url: link }
  if (configured) return { granted: false, status: 'key_ready' }
  return { granted: false, status: 'no_key_in_build' }
}
assert(startPremiumCheckout({}).granted === false, 'checkout never grants without charge')
assert(startPremiumCheckout({ already: true }).status === 'already', 'already subscribed')
assert(startPremiumCheckout({ configured: true }).status === 'key_ready', 'key without payment link')
assert(startPremiumCheckout({ link: 'https://buy.stripe.com/x' }).status === 'redirect', 'payment link redirects')

const explore = filterExploreItems([
  { id: '1', createdAt: new Date().toISOString(), durationSec: 30, views: 2 },
  { id: '2', createdAt: new Date(Date.now() - 40 * 864e5).toISOString(), durationSec: 500, views: 9 },
], { date: 'week', duration: 'short' })
assert(explore.length === 1 && explore[0].id === '1', 'explore date+duration filter')

const checkoutSrc = readFileSync(new URL('../src/lib/checkout.js', import.meta.url), 'utf8')
const pageSrc = readFileSync(new URL('../src/components/CheckoutPage.jsx', import.meta.url), 'utf8')
const modalSrc = readFileSync(new URL('../src/components/CheckoutModal.jsx', import.meta.url), 'utf8')
assert(!checkoutSrc.includes('granted: true'), 'checkout lib never grants')
assert(pageSrc.includes('membershipReturnPaid'), 'checkout page only marks paid after Stripe return')
assert(!modalSrc.includes('addPremiumSub'), 'checkout modal does not fake a paid sub')
assert(pageSrc.includes('startPremiumCheckout'), 'checkout page uses the gate')
assert(modalSrc.includes('startPremiumCheckout'), 'checkout modal uses the gate')
assert(pageSrc.includes('Card checkout') || pageSrc.includes('Payment Link'), 'checkout mentions payment')

const engagementSrc = readFileSync(new URL('../src/lib/engagement.js', import.meta.url), 'utf8')
assert(engagementSrc.includes('export const PREMIUM_PRICE = 5'), 'default list price')
assert(engagementSrc.includes('export function getMembershipPrice'), 'creator list price reader')
assert(engagementSrc.includes('export function setMembershipPrice'), 'creator can set list price')
assert(engagementSrc.includes('n >= 1 && n <= 50'), 'list price stays in range')
assert(engagementSrc.includes('pushFollow'), 'follows push to cloud')
assert(engagementSrc.includes('pushVote'), 'votes push to cloud')

const aboutSrc = readFileSync(new URL('../src/components/AboutPage.jsx', import.meta.url), 'utf8')
assert(aboutSrc.includes('Payouts are not live'), 'about does not promise payouts')
assert(aboutSrc.includes('Live video is not on yet'), 'about labels live honestly')

const authSrc = readFileSync(new URL('../src/components/AuthModal.jsx', import.meta.url), 'utf8')
assert(!authSrc.includes('Continue with Google'), 'google sign-in removed')
assert(authSrc.includes('Continue with Apple'), 'apple sign-in button')
assert(authSrc.includes('Continue with Microsoft'), 'microsoft sign-in button')
assert(authSrc.includes('Continue with X'), 'x sign-in button')
assert(authSrc.includes('loginWithOAuth'), 'oauth handler wired')
assert(authSrc.includes('Phone'), 'phone sign-in')
assert(!/supabase/i.test(authSrc), 'auth modal never says supabase')
assert(authSrc.includes('CapCut cannot sign people'), 'capcut is not a fake login')
assert(!authSrc.includes("&& synced &&"), 'oauth buttons show even when cloud auth is off')

const brandSrc = readFileSync(new URL('../src/lib/authBrand.js', import.meta.url), 'utf8')
assert(brandSrc.includes('Your Clips code is'), 'sms template says clips')
assert(brandSrc.includes('sanitizeAuthError'), 'auth errors are branded')

const secSrc = readFileSync(new URL('../src/components/settings/SecuritySettings.jsx', import.meta.url), 'utf8')
assert(secSrc.includes('startMfaEnroll'), 'real 2fa enroll')
assert(!secSrc.includes('Backend integration required'), '2fa is not a fake checkbox')

const shortsSrc = readFileSync(new URL('../src/components/ShortsFeed.jsx', import.meta.url), 'utf8')
assert(shortsSrc.includes('onStitch'), 'stitch on clip player')
assert(shortsSrc.includes('early_skip'), 'reel skip trains For You')
assert(!shortsSrc.includes('withReferenceShorts'), 'sample clips not mixed into feed')

const gridSrc = readFileSync(new URL('../src/components/ShortsGrid.jsx', import.meta.url), 'utf8')
assert(!gridSrc.includes('>Shorts<'), 'clips page has no Shorts title')
assert(gridSrc.includes('Recommended'), 'clips recommended tab')
assert(gridSrc.includes('Subscribed'), 'clips subscribed tab')

const liveSrc = readFileSync(new URL('../src/components/LiveView.jsx', import.meta.url), 'utf8')
assert(liveSrc.includes('Live video ingest is not connected'), 'live page is a lobby')
assert(!liveSrc.includes('live-badge-glow'), 'no fake glowing LIVE badge')

const mig = readFileSync(new URL('../supabase/migrations/0006_social_graph.sql', import.meta.url), 'utf8')
assert(mig.includes('create table if not exists public.follows'), 'social graph migration')
const graphSrc = readFileSync(new URL('../src/lib/graphSync.js', import.meta.url), 'utf8')
assert(graphSrc.includes('export async function syncGraphFromCloud'), 'cloud graph pull')

const helpSrc = readFileSync(new URL('../src/components/HelpPage.jsx', import.meta.url), 'utf8')
assert(!/467 people/i.test(helpSrc), 'help does not mention named-account bots')
assert(!helpSrc.includes('Copy SQL'), 'help has no SQL copy buttons')
assert(!helpSrc.includes('Open SQL Editor'), 'help has no supabase editor')
assert(!helpSrc.includes('VITE_'), 'help has no env var names')
assert(helpSrc.includes('profile picture') || helpSrc.includes('profile menu'), 'help points studio to the profile menu')

const adminSetupSrc = readFileSync(new URL('../src/components/AdminSetup.jsx', import.meta.url), 'utf8')
assert(adminSetupSrc.includes('Copy'), 'admin setup has copy buttons')
assert(adminSetupSrc.includes('Open SQL Editor'), 'admin setup has a link to the sql editor')
assert(adminSetupSrc.includes('ORG.supabaseSqlEditor'), 'admin setup uses the supabase sql editor url')
assert(adminSetupSrc.includes('0009'), 'admin setup mentions 0009')

const settingsHub = readFileSync(new URL('../src/components/settings/SettingsHub.jsx', import.meta.url), 'utf8')
assert(settingsHub.includes('SecuritySettings'), 'settings hub includes real 2FA page')
const appSrc = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
assert(appSrc.includes('SettingsHub'), 'settings layout is mounted')
assert(appSrc.includes('PasswordRecoveryGate'), 'reset-email landing exists')
assert(!appSrc.includes("from './components/SettingsPage'"), 'old fake-2fa settings page is gone')
const moneySrc = readFileSync(new URL('../src/components/settings/MonetizationSettings.jsx', import.meta.url), 'utf8')
assert(!moneySrc.includes('100% of the listed price'), 'settings does not promise 100% payouts')
assert(!moneySrc.includes('Connect payout method'), 'no fake connect payout button')
const streamSet = readFileSync(new URL('../src/components/settings/StreamSettings.jsx', import.meta.url), 'utf8')
assert(!streamSet.includes('rtmp://'), 'no fake rtmp url')
assert(streamSet.includes('Xbox') && streamSet.includes('PS5'), 'stream settings explain consoles')
assert(streamSet.includes('Live ingest is not connected'), 'stream settings honest')
const copySrc = readFileSync(new URL('../src/components/settings/CopyrightSettings.jsx', import.meta.url), 'utf8')
assert(copySrc.includes('copyright@calabi.us') || copySrc.includes('ORG.copyrightEmail'), 'dmca uses calabi.us')
assert(!copySrc.includes('platform.internal'), 'no internal placeholder emails')

const algoSrc = readFileSync(new URL('../src/lib/algorithmEngine.js', import.meta.url), 'utf8')
assert(algoSrc.includes('explorationRoll'), 'for you exploration is session-stable')
assert(!algoSrc.includes('Math.random()'), 'ranker does not reshuffle every render')
const homeSrc = readFileSync(new URL('../src/components/HomeFeed.jsx', import.meta.url), 'utf8')
assert(homeSrc.includes('getStableHomeFeed'), 'home recommended is frozen until refresh')
const shortsFeedSrc = readFileSync(new URL('../src/components/ShortsFeed.jsx', import.meta.url), 'utf8')
assert(shortsFeedSrc.includes('getStableShortsFeed'), 'clips recommended is frozen until refresh')
const stageSrc = readFileSync(new URL('../src/components/ShortsStage.jsx', import.meta.url), 'utf8')
assert(stageSrc.includes('const loop = false'), 'clips player does not wrap and auto-scroll')
const adsSrc = readFileSync(new URL('../src/components/AdvertisePage.jsx', import.meta.url), 'utf8')
assert(!adsSrc.includes('90%'), 'advertise page does not invent a 90% rev share')
assert(!adsSrc.includes('within 24 hours'), 'advertise page does not promise 24 hour approval')
const applySrc = readFileSync(new URL('../src/components/CreatorApplyPage.jsx', import.meta.url), 'utf8')
assert(applySrc.includes('What is not live'), 'creator apply lists what is not shipped')
assert(applySrc.includes('CONTENT_RULES_SHORT'), 'creator apply shows content rules')
const adEng = readFileSync(new URL('../src/lib/adEngine.js', import.meta.url), 'utf8')
assert(adEng.includes('clips_ads_running'), 'ads have a global on/off switch')
assert(adEng.includes('if (!adsAreRunning()) return null'), 'preroll stays off until admin enables ads')
assert(adEng.includes('mixFeedAds'), 'clip and pic feeds can insert ads between items')
assert(adEng.includes("provider: 'exoclick'"), 'clip and pic feeds use the ExoClick display zone')
assert(adEng.includes('clipFeedEvery: 4'), 'clip ads sit every 4 items like Shorts')
assert(adEng.includes('n % 15 === 0'), 'clip banners sit about every 15 clips')
assert(shortsFeedSrc.includes('mixFeedAds'), 'clip player inserts ads between clips')
assert(adEng.includes('clip-banner') && adEng.includes('pic-feed'), 'clip and pic placements exist')
const paySrc = readFileSync(new URL('../src/lib/payouts.js', import.meta.url), 'utf8')
assert(!paySrc.includes('rpmPerThousand'), 'payouts are not a per-1000-views rate')
assert(!paySrc.includes('DEFAULT_RPM'), 'no default view rpm')
assert(paySrc.includes('recordManualPayout'), 'admin can mark a hand payout sent')
assert(applySrc.includes('Apply to earn'), 'apply page is for earning not posting')
const adminSrc = readFileSync(new URL('../src/components/AdminPortal.jsx', import.meta.url), 'utf8')
assert(adminSrc.includes("id: 'payouts'"), 'admin has a payouts tab')
assert(adminSrc.includes("id: 'setup'"), 'admin has a setup tab for sql')
assert(adminSrc.includes("id: 'people'"), 'admin has a people workspace')
assert(adminSrc.includes('AdminSetup'), 'admin setup is not on Help')
assert(adminSrc.includes('AdminAds'), 'admin ads tab is its own panel')
assert(adminSrc.includes('AdminPeople'), 'admin people table is editable')
const trustSrc = readFileSync(new URL('../src/lib/trustSafety.js', import.meta.url), 'utf8')
assert(trustSrc.includes('export function banUser'), 'admin can ban people')
assert(trustSrc.includes('export function suspendUser'), 'admin can suspend people')
assert(trustSrc.includes('export function holdPayouts'), 'admin can hold payouts')
assert(trustSrc.includes('export function adminUpdateProfile'), 'admin can edit profiles')
assert(trustSrc.includes('export function addStrike'), 'admin can issue youtube-style strikes')
const adminAdsSrc = readFileSync(new URL('../src/components/AdminAds.jsx', import.meta.url), 'utf8')
assert(adminAdsSrc.includes('Ads are off'), 'admin can leave ads off')
assert(adminAdsSrc.includes('Where ads show'), 'admin can toggle each placement')
assert(adminAdsSrc.includes('clipBanner') && adminAdsSrc.includes('picInFeed'), 'admin has clip and pic placement switches')
const shortsGridSrc = readFileSync(new URL('../src/components/ShortsGrid.jsx', import.meta.url), 'utf8')
assert(shortsGridSrc.includes('mixFeedAds'), 'clip grid inserts in-feed ads')
assert(shortsFeedSrc.includes('clipBannerAllowed'), 'clip player has banners under the description')
assert(shortsFeedSrc.includes('EXOCLICK_BANNER_ZONE'), 'clip banners use the ExoClick banner zone')
const exoSrc = readFileSync(new URL('../src/components/ExoClickDisplay.jsx', import.meta.url), 'utf8')
assert(exoSrc.includes('6010930') && exoSrc.includes('eas6a97888e2'), 'clip banner zone id is 6010930')
const picsSrc = readFileSync(new URL('../src/components/PicsPage.jsx', import.meta.url), 'utf8')
assert(picsSrc.includes('mixFeedAds'), 'pic mosaic inserts in-feed ads')
assert(picsSrc.includes('pic-banner'), 'pic viewer has a bottom banner')
assert(picsSrc.includes('ExoClickDisplay'), 'pic viewer inserts full ads between photos')
const watchAds = readFileSync(new URL('../src/components/WatchPage.jsx', import.meta.url), 'utf8')
assert(watchAds.includes('VideoInStreamAd'), 'watch plays VAST in-stream ads on videos')
assert(watchAds.includes('useVideoVastAds'), 'watch loads ExoClick VAST for videos')
assert(!shortsFeedSrc.includes('useVideoVastAds'), 'clips do not play VAST preroll')
const dashSrc = readFileSync(new URL('../src/components/CreatorDashboard.jsx', import.meta.url), 'utf8')
assert(dashSrc.includes('Copy stream key'), 'creator dashboard has stream key')
assert(dashSrc.includes('Wallet'), 'creator dashboard links wallet')
const vodLib = readFileSync(new URL('../src/lib/vods.js', import.meta.url), 'utf8')
assert(vodLib.includes('archiveEndedLive'), 'ended lives are copied')
assert(vodLib.includes('setVodChannel'), 'creators can enable a VOD channel')
const ownerSrc = readFileSync(new URL('../src/data/ownerLogin.js', import.meta.url), 'utf8')
assert(ownerSrc.includes('cs1@calabi.local'), 'owner login email exists')
assert(ownerSrc.includes('passwordHash'), 'owner password is hashed')
assert(!!findOwnerLogin('cs1'), 'owner sign-in accepts handle cs1')
assert(!!findOwnerLogin('sa6sysn'), 'owner sign-in accepts sa6sysn')
assert(!!findOwnerLogin('cs1@calabi.local'), 'owner sign-in accepts local email')
assert(!!findOwnerLogin('kiddnixk@gmail.com'), 'owner sign-in accepts gmail')
assert(isLocalOwnerLogin('cs1') && !isLocalOwnerLogin('kiddnixk@gmail.com'), 'gmail can fall through to cloud auth')
assert(!findOwnerLogin('name1@calabi.com'), 'named accounts are not owner')
function ownerHashMatches(raw, stored) {
  const parts = String(stored || '').split('$')
  if (parts.length < 3) return false
  const next = createHash('sha256').update(`${parts[1]}:${raw}`).digest('hex')
  return next === parts[2]
}
const ownerHashes = [OWNER_LOGIN.passwordHash, ...(OWNER_LOGIN.passwordHashes || [])]
assert(ownerHashes.some((h) => ownerHashMatches('cs1cs1', h)), 'simple owner password hash is stored')
assert(isOwnerAccount({ id: 'owner-cs1', handle: 'cs1' }), 'cs1 account is owner')
const modSrc = readFileSync(new URL('../src/lib/moderation.js', import.meta.url), 'utf8')
assert(modSrc.includes('if (isPlatformOwner(user)) return true'), 'signed-in owner skips a second admin password')
assert(modSrc.includes('ownerPasswordHashes'), 'admin login accepts the site owner password')
const avatarSrc = readFileSync(new URL('../src/components/ChannelAvatar.jsx', import.meta.url), 'utf8')
assert(!avatarSrc.includes('VerifiedBadge'), 'checkmarks are not on profile pictures')
assert(!avatarSrc.includes('official'), 'avatars do not take an official badge prop')
const modalSrcAuth = readFileSync(new URL('../src/components/AuthModal.jsx', import.meta.url), 'utf8')
assert(modalSrcAuth.includes('findOwnerLogin'), 'auth modal allows owner username without @')
const authOwner = readFileSync(new URL('../src/context/AuthContext.jsx', import.meta.url), 'utf8')
assert(authOwner.includes('findOwnerLogin'), 'sign-in intercepts owner email')
assert(authOwner.includes('passwordHashes'), 'sign-in checks every owner password hash')
assert(authOwner.includes('isLocalOwnerLogin'), 'gmail password can use cloud auth if hashes miss')
const streamSet2 = readFileSync(new URL('../src/components/settings/StreamSettings.jsx', import.meta.url), 'utf8')
assert(streamSet2.includes('ensureStreamKey'), 'stream settings expose a key')
assert(streamSet2.includes('Enable VOD channel'), 'stream settings have VOD channel')
assert(algoSrc.includes('bumpCatalogEngagement'), 'watch signals write back onto posts')
assert(!algoSrc.includes('valorant'), 'search does not invent trending queries')

const creatorsSrc = readFileSync(new URL('../src/components/CreatorsPage.jsx', import.meta.url), 'utf8')
assert(creatorsSrc.includes('listSidebarCreators'), 'creators page ranks people who posted')

const healthSrc = readFileSync(new URL('../src/lib/catalogHealth.js', import.meta.url), 'utf8')
assert(healthSrc.includes('purgeDeadCatalog'), 'dead pics and sample clips are purged')

const purgeSql = readFileSync(new URL('../supabase/migrations/0007_purge_dead_media.sql', import.meta.url), 'utf8')
assert(purgeSql.includes("type = 'pic'"), 'sql removes unplayable pics')

const purgeSql8 = readFileSync(new URL('../supabase/migrations/0008_purge_dead_media.sql', import.meta.url), 'utf8')
assert(purgeSql8.includes('picsum'), 'sql 0008 removes leftover sample hosts')

const profileMedia = readFileSync(new URL('../src/lib/profileMedia.js', import.meta.url), 'utf8')
assert(profileMedia.includes('persistProfilePicture'), 'profile photos persist outside localStorage quota')
const channelSrc = readFileSync(new URL('../src/components/ChannelPage.jsx', import.meta.url), 'utf8')
assert(channelSrc.includes('Saved as you type'), 'channel saves while you type')
assert(channelSrc.includes('Change profile picture'), 'avatar camera is on the photo')

const cardSrc = readFileSync(new URL('../src/components/ContentCard.jsx', import.meta.url), 'utf8')
assert(cardSrc.includes('PostedStamp'), 'home cards show real post time')
assert(cardSrc.includes('viewsLabel'), 'cards format view counts')
assert(cardSrc.includes('Download'), 'cards can download a post')
assert(cardSrc.includes('VerifiedBadge'), 'cards put the checkmark beside the name')
assert(!cardSrc.includes('official={official}'), 'cards do not put the checkmark on the avatar')
const watchSrc2 = readFileSync(new URL('../src/components/WatchPage.jsx', import.meta.url), 'utf8')
assert(watchSrc2.includes('downloadPostedMedia'), 'watch page can download')
const dlSrc = readFileSync(new URL('../src/lib/mediaDownload.js', import.meta.url), 'utf8')
assert(dlSrc.includes('Anyone can save'), 'downloads are public')
const vidStore = readFileSync(new URL('../src/lib/videoStorage.js', import.meta.url), 'utf8')
assert(vidStore.includes('transcodeVideoForUpload'), 'uploads are transcoded for space')
const pubSrc = readFileSync(new URL('../src/lib/contentService.js', import.meta.url), 'utf8')
assert(pubSrc.includes('transcodeVideoForUpload'), 'publish path uses the transcode')
const navSrc = readFileSync(new URL('../src/components/StreamingNavbar.jsx', import.meta.url), 'utf8')
assert(!navSrc.includes('SiteClock'), 'header does not show a site clock')
assert(navSrc.includes('withWord'), 'header shows the calabi wordmark')
assert(!navSrc.includes('handleNav(\'live\')'), 'header does not show Live Recommended Explore Clips')
assert(!/\bRecommended\b/.test(navSrc) && !/\bExplore\b/.test(navSrc) && !/\bClips\b/.test(navSrc), 'header has no Recommended Live Explore Clips chips')
const sideSrc = readFileSync(new URL('../src/components/CollapsibleSidebar.jsx', import.meta.url), 'utf8')
assert(sideSrc.includes('Top creators'), 'sidebar heading is Top creators')
assert(sideSrc.includes('label="Subscribed"'), 'sidebar following renamed subscribed')
assert(!sideSrc.includes('Creator Dashboard'), 'sidebar has no creator dashboard')
assert(!sideSrc.includes('label="Wallet"'), 'sidebar has no wallet')
assert(!sideSrc.includes('label="Analytics"'), 'sidebar has no analytics')
assert(!sideSrc.includes('Apply to create'), 'sidebar has no creator application')
assert(navSrc.includes('Creator Dashboard'), 'profile menu has creator dashboard')
assert(navSrc.includes('> Analytics'), 'profile menu has analytics')
assert(navSrc.includes('> Wallet'), 'profile menu has wallet')
assert(navSrc.includes('> VODs'), 'profile menu has vods')
assert(sideSrc.includes('min-h-0 overflow-y-auto'), 'sidebar still scrolls')
assert(sideSrc.includes('label="Create"'), 'sidebar has Create under Live')
assert(!sideSrc.includes('label="Notifications"'), 'notifications are not a sidebar tab')
assert(sideSrc.includes('if (!open) return null'), 'sidebar starts closed until the hamburger opens it')
assert(navSrc.includes('d + 90'), 'hamburger makes full 90 degree turns')
assert(navSrc.includes('flex h-14 w-14 items-center justify-center text-zinc-200"'), 'hamburger has no grey hover fill')
assert(appSrc.includes('migrateHashToPath'), 'old hash urls redirect to paths')
assert(!appSrc.includes('hashchange'), 'routing is not hash-based')
assert(!appSrc.includes("user?.creatorStatus !== 'approved'"), 'going live is not locked behind apply')
assert(!navSrc.includes('aria-label="Create"'), 'header has no Create button')
const notifMenu = readFileSync(new URL('../src/components/NotificationsMenu.jsx', import.meta.url), 'utf8')
assert(notifMenu.includes('slice(0, 5)'), 'header bell shows about five notifications')
assert(notifMenu.includes('Show more'), 'bell dropdown leads to the notifications page')
const subBtn = readFileSync(new URL('../src/components/SubscribeButton.jsx', import.meta.url), 'utf8')
assert(subBtn.includes('Subscribe'), 'subscribe button exists')
assert(!subBtn.includes('Follow'), 'follow label is gone')
assert(subBtn.includes('onOpenAuth'), 'subscribe opens sign-in when logged out')
const creatorPageSrc = readFileSync(new URL('../src/components/ProfilePage.jsx', import.meta.url), 'utf8')
assert(creatorPageSrc.includes('SubscribeButton'), 'creator page has subscribe')
const uploadSrc = readFileSync(new URL('../src/components/UploadModal.jsx', import.meta.url), 'utf8')
assert(uploadSrc.includes('priceUsd'), 'creators can price a post')
assert(watchSrc2.includes('clips_pending_purchase'), 'paid posts wait for Stripe return')
assert(watchSrc2.includes('Paid post'), 'watch shows paid overlay')
assert(watchSrc2.includes('NextStrip'), 'watch uses a horizontal next strip, not a YouTube right rail')
assert(!watchSrc2.includes('RelatedRow'), 'watch does not clone the YouTube related column')
const verifyLib = readFileSync(new URL('../src/lib/verification.js', import.meta.url), 'utf8')
assert(verifyLib.includes('frontFile') && verifyLib.includes('backFile'), 'checkmark needs front and back of ID')
assert(verifyLib.includes("status === 'approved'") || verifyLib.includes("nextStatus = status === 'approved'"), 'admin can accept an ID')
assert(verifyLib.includes("'denied'"), 'admin can deny an ID')
assert(verifyLib.includes('isOfficialCreator'), 'official channels keep checkmarks without ID')
assert(verifyLib.includes('isVerifiedChannel'), 'badges use official or accepted ID')
const verifyPage = readFileSync(new URL('../src/components/VerifyPage.jsx', import.meta.url), 'utf8')
assert(verifyPage.includes('Front of ID') && verifyPage.includes('Back of ID'), 'verify page asks for both sides')
assert(verifyPage.includes('with or without creator status'), 'checkmark is independent of creator status')
const adminSafetySrc = readFileSync(new URL('../src/components/admin/AdminSafety.jsx', import.meta.url), 'utf8')
assert(adminSafetySrc.includes('ID checks'), 'admin has ID checks tab')
assert(adminSafetySrc.includes('Accept') && adminSafetySrc.includes('Deny'), 'admin can accept or deny ID')
assert(adminSafetySrc.includes('setIdVerificationStatus'), 'admin writes ID review')
assert(appSrc.includes('VerifyPage'), 'verify route is mounted')
assert(appSrc.includes("'verify'"), 'verify is a known view')
const channelSet = readFileSync(new URL('../src/components/settings/ChannelSettings.jsx', import.meta.url), 'utf8')
assert(channelSet.includes('Get a checkmark') || channelSet.includes('View checkmark'), 'settings links to ID checkmark')
assert(!channelSet.includes('There is no verification queue yet'), 'settings no longer says checkmark is missing')
const stampSrc = readFileSync(new URL('../src/components/PostedStamp.jsx', import.meta.url), 'utf8')
assert(stampSrc.includes('formatPostedAt'), 'posted stamp ages over time')

const kidsSrc = readFileSync(new URL('../src/data/publicMediaSeed.js', import.meta.url), 'utf8')
assert(kidsSrc.includes("handle: 'nasa'"), 'nasa creator channel')
assert(kidsSrc.includes('yt3.googleusercontent.com'), 'library channels use YouTube avatars')
assert(kidsSrc.includes('bpfrBmM6vZk'), 'nasa connect uses eClips youtube art')
assert(kidsSrc.includes('official-pd-v6'), 'catalog generation refreshes timestamps')
assert(!kidsSrc.includes('1969-07-24'), 'library posts are dated today not 1969')
assert(kidsSrc.includes("handle: 'noaa'"), 'noaa creator channel')
assert(kidsSrc.includes("handle: 'esa'"), 'esa creator channel')
assert(kidsSrc.includes("handle: 'nasaconnect'"), 'nasa connect kids channel')
assert(kidsSrc.includes("handle: 'classroom'"), 'classroom films channel')
assert(kidsSrc.includes("handle: 'nara'"), 'national archives channel')
assert(kidsSrc.includes('archive.org/download'), 'archive.org documentaries')
assert(kidsSrc.includes("'kids'"), 'kids tagged films')
assert(kidsSrc.includes("'maths'"), 'maths films')
assert(kidsSrc.includes("'english'"), 'english films')
assert(kidsSrc.includes("'history'"), 'history films')
assert(kidsSrc.includes("'documentary'"), 'documentaries')
assert(kidsSrc.includes('durationSec: 1710'), 'long nasa connect programme')
assert(kidsSrc.includes('durationSec: 3140'), 'long history documentary')
assert(kidsSrc.includes("creatorStatus: 'approved'"), 'official channels are creators')
assert(kidsSrc.includes('https://images-assets.nasa.gov'), 'nasa public media')
assert(kidsSrc.includes('https://upload.wikimedia.org'), 'commons public media')
assert(!/oraknebara|or%c3%a4knebara|substantiv/i.test(kidsSrc), 'no foreign-language nouns video')
assert(!/picsum|placekitten|sample-videos|gtv-videos/i.test(kidsSrc), 'official media is not placeholder hosts')
assert(kidsSrc.includes("type: 'video'"), 'official library has videos')
assert(kidsSrc.includes("type: 'short'"), 'official library has clips')
assert(kidsSrc.includes("type: 'pic'"), 'official library has photos')
assert(kidsSrc.includes("lsSet(GEN_KEY, CATALOG_GENERATION)"), 'catalog generation is stored so dates refresh')
assert(kidsSrc.includes('export function findOfficialLogin'), 'library channels have site logins')
assert((kidsSrc.match(/email: '[\w.]+@calabi\.local'/g) || []).length >= 7, 'each official channel has a site email')
assert((kidsSrc.match(/passwordHash: 'sha256\$/g) || []).length >= 7, 'channel passwords are hashed not stored in the open')
const authCtx = readFileSync(new URL('../src/context/AuthContext.jsx', import.meta.url), 'utf8')
assert(authCtx.includes('findOfficialLogin'), 'sign-in intercepts library channel emails')
assert(authCtx.includes('findOwnerLogin'), 'owner login runs in auth')
assert(authCtx.indexOf('findOfficialLogin') < authCtx.indexOf('signInWithPassword'), 'library logins run before cloud auth')
assert(authCtx.includes('findNamedAccountLogin'), 'named people accounts can sign in')
assert(authCtx.indexOf('findNamedAccountLogin') < authCtx.indexOf('signInWithPassword'), 'named logins run before cloud auth')
const namedCsv = readFileSync(new URL('../src/data/namedAccounts.csv', import.meta.url), 'utf8').trim().split(/\n/)
assert(namedCsv.length === 468, '467 named accounts plus header')
assert(namedCsv[1].startsWith('1,Lucy,Bennett,'), 'first named account is Lucy Bennett')
assert(namedCsv[467].startsWith('467,Sophia,Wood,'), 'last named account is Sophia Wood')
const namedSrc = readFileSync(new URL('../src/data/namedAccountsSeed.js', import.meta.url), 'utf8')
assert(namedSrc.includes("name${n}@calabi.com"), 'named emails are nameN@calabi.com')
assert(namedSrc.includes("Hoka${String(id).padStart(4, '0')}"), 'named passwords follow Hoka0001 pattern')
assert(namedSrc.includes("BLACK_PROFILE_URL = '/media/black.png'"), 'named accounts use the black profile image')
const blackPng = readFileSync(new URL('../public/media/black.png', import.meta.url))
assert(blackPng[0] === 0x89 && blackPng[1] === 0x50 && blackPng[2] === 0x4e && blackPng[3] === 0x47, 'black profile file is a png')
const profileSrc = readFileSync(new URL('../src/lib/profileMedia.js', import.meta.url), 'utf8')
assert(profileSrc.includes('isSiteProfileAsset'), 'black site avatars are allowed to persist')
const healSrc = readFileSync(new URL('../src/lib/selfHeal.js', import.meta.url), 'utf8')
assert(healSrc.includes('seedOfficialCatalog'), 'official catalog seeds on boot')
assert(healSrc.includes('seedNamedAccounts'), 'named people accounts seed on boot')
assert(!healSrc.includes('seedKidsEducation'), 'kids filler seed is gone')
const healthSrc2 = readFileSync(new URL('../src/lib/catalogHealth.js', import.meta.url), 'utf8')
assert(healthSrc2.includes('isRetiredCatalogItem'), 'old kids seed rows cannot return')

const namedAct = readFileSync(new URL('../src/lib/namedAccountActivity.js', import.meta.url), 'utf8')
assert(namedAct.includes('ensureUpvote'), 'named accounts like with ensureUpvote')
assert(namedAct.includes("type: 'upvote'"), 'named likes are upvotes')
assert(!namedAct.includes('toggleVote'), 'named accounts do not toggle likes off')
assert(!namedAct.includes('postLiveChat'), 'named accounts do not chat in live')
assert(!namedAct.includes('addComment'), 'named accounts do not comment')
assert(namedAct.includes('getHomeFeed'), 'named accounts scroll recommended')
assert(namedAct.includes('getShortsFeed'), 'named accounts scroll clips')
assert(namedAct.includes('getPicsFeed'), 'named accounts scroll pics')
assert(namedAct.includes('sitInOneLive'), 'named accounts watch live lobbies')
assert(namedAct.includes('Math.random'), 'named accounts pick random items')
const appSrc2 = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
assert(appSrc2.includes('startNamedAccountActivity'), 'named activity starts with the app')
const engSrc = readFileSync(new URL('../src/lib/engagement.js', import.meta.url), 'utf8')
assert(engSrc.includes('export function ensureUpvote'), 'likes can be applied without unliking')
const namedSql = readFileSync(new URL('../supabase/migrations/0009_named_activity.sql', import.meta.url), 'utf8')
assert(namedSql.includes('create table if not exists public.named_people'), '0009 stores the 467 people')
assert((namedSql.match(/named-\d{4}/g) || []).length >= 467, '0009 seeds 467 named ids')
assert(namedSql.includes('run_named_activity'), '0009 is the supabase activity job')
assert(namedSql.includes("values (pid, cid, 'up')"), 'job only inserts up votes')
assert(!/insert into public\.comments/i.test(namedSql), 'job never comments')
assert(!/live_chat/i.test(namedSql), 'job never writes live chat')
assert(namedSql.includes('order by random()'), 'sql job picks random people and videos')
assert(!namedSql.includes('offset ((cur / n_people)'), 'sql job is not a fixed lockstep cursor')
assert(namedSql.includes('cron.schedule'), 'job is scheduled in the database')
assert(namedSql.includes('on conflict (user_id, content_id) do nothing'), 'likes are never removed')
const scriptsSrc = readFileSync(new URL('../src/data/supabaseScripts.js', import.meta.url), 'utf8')
assert(scriptsSrc.includes('0009_named_activity.sql'), 'admin can copy 0009')
const orgSrc = readFileSync(new URL('../src/lib/orgConfig.js', import.meta.url), 'utf8')
assert(orgSrc.includes('supabase.com/dashboard/project/'), 'sql editor url is the supabase dashboard')
const namedAct2 = readFileSync(new URL('../src/lib/namedAccountActivity.js', import.meta.url), 'utf8')
assert(namedAct2.includes('startNamedAccountActivity'), 'named activity has a starter')
assert(namedAct2.includes('setInterval'), 'named bots keep running in the open site')
const graphSrc2 = readFileSync(new URL('../src/lib/graphSync.js', import.meta.url), 'utf8')
assert(graphSrc2.includes('syncPublicEngagementFromCloud'), 'clients pull like tallies without signing in')
assert(graphSrc2.includes('vote_tallies'), 'like counts come from vote_tallies')

const before31 = new Date(2026, 7, 24, 14, 10, 0).getTime()
const at31 = new Date(2026, 7, 24, 14, 31, 0).getTime()
const startBefore = new Date(featuredWindowStart(before31))
assert(startBefore.getHours() === 13 && startBefore.getMinutes() === 31, 'before :31 the lineup is from last hour :31')
const startAt = new Date(featuredWindowStart(at31))
assert(startAt.getHours() === 14 && startAt.getMinutes() === 31, 'at :31 the lineup refreshes')
assert(nextFeaturedRefreshAt(at31) === featuredWindowStart(at31) + 3600000, 'next refresh is one hour later')
const range = lastHourRange(at31)
assert(range.end - range.start === 3600000, 'ranking window is the previous hour')
assert(HOURLY_PATTERN.filter((t) => t === 'video').length === HOURLY_VIDEO_COUNT, 'stage mix has 5 videos')
assert(HOURLY_PATTERN.filter((t) => t === 'short').length === HOURLY_CLIP_COUNT, 'stage mix has 10 clips')
assert(HOURLY_PATTERN.filter((t) => t === 'pic').length === HOURLY_PIC_COUNT, 'stage mix has 3 pics')
const mixed = interleaveHourlyHits(
  Array.from({ length: 5 }, (_, i) => ({ id: `v${i}`, type: 'video' })),
  Array.from({ length: 10 }, (_, i) => ({ id: `c${i}`, type: 'short' })),
  Array.from({ length: 3 }, (_, i) => ({ id: `p${i}`, type: 'pic' })),
)
assert(mixed.length === 18, 'hourly stage holds 18 posts when the catalog is full')
assert(mixed.filter((i) => i.type === 'video').length === 5, 'interleave keeps 5 videos')
assert(mixed.filter((i) => i.type === 'short').length === 10, 'interleave keeps 10 clips')
assert(mixed.filter((i) => i.type === 'pic').length === 3, 'interleave keeps 3 pics')
const homeSrc2 = readFileSync(new URL('../src/components/HomeFeed.jsx', import.meta.url), 'utf8')
assert(homeSrc2.includes('HourlyHitsCarousel'), 'home puts the hourly stage under the search bar')
const carouselSrc = readFileSync(new URL('../src/components/HourlyHitsCarousel.jsx', import.meta.url), 'utf8')
assert(carouselSrc.includes('ChevronLeft') && carouselSrc.includes('ChevronRight'), 'hourly stage has twitch-style arrows')
assert(!carouselSrc.includes('New lineup at'), 'hourly stage has no lineup clock copy')
assert(!carouselSrc.includes('Last hour'), 'hourly stage has no last-hour label')
assert(!carouselSrc.includes('typeMeta'), 'hourly stage does not stamp clip/video/pic')
const hitsSrc = readFileSync(new URL('../src/lib/hourlyHits.js', import.meta.url), 'utf8')
assert(hitsSrc.includes('engagement_views') && hitsSrc.includes('clips_content_views'), 'stage ranks on all stored views')
assert(!hitsSrc.includes('hourViewCount'), 'stage is not ranked on last-hour-only views')
const engagementHits = readFileSync(new URL('../src/lib/engagement.js', import.meta.url), 'utf8')
assert(engagementHits.includes('recordHourView'), 'views in the last hour are counted for the stage')
const miniSrc = readFileSync(new URL('../src/components/MiniPlayer.jsx', import.meta.url), 'utf8')
assert(miniSrc.includes('top-[3.75rem]') && miniSrc.includes('right-3'), 'docked watch player sits top right')
assert(!miniSrc.includes('bottom-3 right-3'), 'docked watch player is not bottom right')
const tipsSrc = readFileSync(new URL('../src/lib/tips.js', import.meta.url), 'utf8')
assert(tipsSrc.includes('membershipReturnPaid'), 'tips wait for a Stripe return')
assert(tipsSrc.includes('live_tip') && tipsSrc.includes('post_tip'), 'live and post tips exist')
assert(!tipsSrc.includes('granted: true'), 'tips never grant access without the checkout gate')
assert(appSrc.includes('claimStripeReturn'), 'app applies Stripe returns in one place')
const chatLib = readFileSync(new URL('../src/lib/liveChat.js', import.meta.url), 'utf8')
assert(chatLib.includes('trySendLiveChat'), 'live chat enforces slow mode and bans')
assert(chatLib.includes('!rules'), 'chat bots reply to !rules')
const rolesSrc = readFileSync(new URL('../src/components/settings/RolesSettings.jsx', import.meta.url), 'utf8')
assert(rolesSrc.includes('addRole'), 'streamers can assign mods')
assert(rolesSrc.includes('addBotCommand'), 'streamers can add bot commands')
assert(!rolesSrc.includes('not assignable yet'), 'roles are no longer a placeholder')
assert(settingsHub.includes('CommentSettings'), 'comments settings page is mounted')
const commentSet = readFileSync(new URL('../src/components/settings/CommentSettings.jsx', import.meta.url), 'utf8')
assert(commentSet.includes('showDonationsOnComments'), 'comment settings can hide donation amounts')
const liveViewSrc = readFileSync(new URL('../src/components/LiveView.jsx', import.meta.url), 'utf8')
assert(liveViewSrc.includes('getDisplayMedia'), 'PC screen share uses the browser capture API')
assert(liveSrc.includes('getDisplayMedia') || liveViewSrc.includes('Share this screen'), 'live has share this screen')
const panelSrc = readFileSync(new URL('../src/components/LiveChatPanel.jsx', import.meta.url), 'utf8')
assert(panelSrc.includes('startTipCheckout'), 'live chat has donate amounts')
assert(panelSrc.includes("kind === 'donation'"), 'live donations render in chat')

{
  let live = null
  for (let i = 0; i < 2 && !live?.mediaUrl; i += 1) {
    try {
      const xml = execFileSync('curl', ['-fsS', '-A', 'Mozilla/5.0', EXOCLICK_VAST_URL], { encoding: 'utf8', timeout: 12000 })
      live = parseVastXml(xml)
    } catch {
      live = null
    }
  }
  assert(!!live?.mediaUrl, 'live exoClick vast returns a playable file')
}

if (failed) {
  console.error(`${failed} failed`)
  process.exit(1)
}
console.log('all smoke checks passed')
